<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>icon.ico</ApplicationIcon>
		<AssemblyTitle>ColorTrack - VACS Analyzer</AssemblyTitle>
		<AssemblyDescription>Color chromaticity analysis tool for viewing angle color shift measurement</AssemblyDescription>
		<AssemblyCompany>ColorTrack</AssemblyCompany>
		<AssemblyProduct>ColorTrack</AssemblyProduct>
		<AssemblyCopyright>Copyright © 2024 ColorTrack</AssemblyCopyright>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OxyPlot.Core" Version="2.1.2" />
		<PackageReference Include="OxyPlot.WindowsForms" Version="2.1.2" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Images\" />
		<Folder Include="Images\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Images\cie1931_background_clean.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Images\cie1976_background_clean.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>