# -*- coding: utf-8 -*-
"""Prose content (ko/en/ja/zh) for the Color Science Part 1 post.
Kept in its own importable module to avoid shell-escaping issues.
HTML-light: <p>, <strong>, <i> only. Each section names a figure key."""


def content(lang):
    C = {}
    C["ko"] = dict(
        title="색의 과학 ① 우리는 어떻게 색을 보는가 — 전자기파에서 대뇌피질까지",
        desc="빛은 어떻게 '색'이 되는가. 전자기파, 가시광선이 가시광선인 이유, 눈의 간상·원추세포, L·M·S 원추의 광전변환, 시신경에서 대뇌피질까지를 직접 그린 도표로 아주 쉽게 풀어낸 색채과학 입문.",
        keywords="색채과학, 색 인지, 전자기파, 가시광선, 원추세포, 간상세포, LMS, 광전변환, 옵신, 반대색, 시각피질, 디스플레이 광학, lucky please",
        og_title="우리는 어떻게 색을 보는가 — 전자기파에서 대뇌피질까지",
        og_desc="빨강이라는 파장은 없다. 빛이 물리량에서 색 경험으로 바뀌는 전 과정을 도표로 풀었다. 색의 과학 1부.",
        kicker="색의 과학 · 1부", h1="우리는 어떻게 색을 보는가",
        sub="전자기파에서 대뇌피질까지 — 빛이 '색'이라는 경험으로 바뀌는 전 과정",
        lead="색은 바깥 세계에 칠해진 물감이 아니다. '빨강'이라는 파장은 어디에도 존재하지 않는다. 색은 빛이라는 물리 현상과, 그것을 받아 해석하는 눈·신경·뇌가 함께 빚어내는 <strong>경험</strong>이다. 이 글은 그 첫 단계, 빛이 물리량에서 색 경험으로 바뀌는 과정을 한 걸음씩 따라간다.",
        secs=[
            dict(h2="1. 빛이라는 전자기파", fig="em",
                 cap="전자기파 스펙트럼. 수 km짜리 전파부터 감마선까지의 거대한 띠에서, 우리 눈이 반응하는 구간은 380–700nm의 극히 일부다.",
                 paras=["빛은 전기장과 자기장이 서로를 밀어내며 공간을 가로지르는 파동, 즉 <strong>전자기파</strong>다. 파장(또는 진동수)이 그 파동의 성격을 결정한다. 파장이 길면 에너지가 낮고, 짧으면 높다.",
                        "전자기파의 스펙트럼은 상상 이상으로 넓다. 수 킬로미터짜리 전파에서 시작해 마이크로파·적외선을 지나, 우리가 보는 좁은 띠를 넘어, 자외선·X선·원자보다 작은 감마선까지 이어진다. 그 거대한 스펙트럼에서 인간의 눈이 반응하는 구간은 대략 <strong>380nm에서 700nm</strong>, 전체의 한 줌도 안 되는 폭이다."]),
            dict(h2="2. 가시광선은 왜 '가시'광선인가", fig="win",
                 cap="약 5800K 태양 복사(금색)는 가시광 영역에서 세기가 정점을 이루고, 대기·물의 투과율(파란 점선)은 바로 그 구간에 '창'을 연다. 두 사실이 겹치는 곳이 가시광선이다.",
                 paras=["왜 하필 이 좁은 띠일까? 우연이 아니라 두 가지 물리적 사실이 겹친 결과다. 첫째, 지구에 쏟아지는 태양 복사는 약 5800K 흑체 복사에 가깝고, 그 세기는 마침 가시광 영역에서 <strong>정점</strong>을 이룬다. 둘째, 지구의 대기와 물은 자외선은 오존으로 막고 적외선은 상당 부분 흡수하지만, 가시광 영역에는 거의 투명한 <strong>'창'</strong>을 열어준다.",
                        "즉 지표면에 가장 풍부하게, 가장 또렷하게 도달하는 빛이 바로 이 띠다. 생명은 정보가 가장 풍부한 신호에 감각기를 맞춰 진화했다. 다시 말해 가시광선이 '보이는' 이유는 빛 자체의 특별함이 아니라, <strong>그 빛에 맞춰 만들어진 우리 눈의 사정</strong>이다. 박쥐에게 가시광선이 소리라면, 우리에게 그것은 색이다."]),
            dict(h2="3. 눈 — 빛이 도착하는 곳", fig="eye",
                 cap="빛은 수정체를 지나 망막에 맺힌다. 망막의 두 광수용체 중 간상세포는 명암·야간시를, 원추세포는 색을 담당한다.",
                 paras=["빛은 각막과 수정체를 지나 눈 안쪽 벽인 <strong>망막</strong>에 상으로 맺힌다. 망막에는 빛을 전기 신호로 바꾸는 광수용체가 두 종류 있다.",
                        "<strong>간상세포</strong>(rod)는 약 1.2억 개로 극도로 민감해 어두운 곳과 명암을 담당하지만, 색은 구분하지 못한다. 밤에 세상이 회색으로 보이는 이유다. <strong>원추세포</strong>(cone)는 약 600만 개로 밝은 곳에서 작동하며 색을 만든다. 원추세포는 시야 중심의 <strong>중심와</strong>(fovea)에 빽빽이 모여 있다. 무언가를 '똑바로 응시할 때' 가장 선명하고 색이 풍부하게 보이는 건 그 때문이다."]),
            dict(h2="4. L·M·S — 세 개의 채널", fig="lms",
                 cap="L·M·S 원추세포의 분광 감도. 각 세포는 한 파장만 보는 게 아니라 넓게 반응하고, 세 곡선은 크게 겹친다. 색은 이 세 응답의 '비율'이다.",
                 paras=["색의 출발점은 놀랍게도 단 <strong>세 종류</strong>의 원추세포다. 각각 장파장(L)·중파장(M)·단파장(S)에 가장 민감하며, 감도의 정점은 대략 L 564nm, M 534nm, S 420nm 부근이다.",
                        "핵심은 각 세포가 '한 파장만' 감지하는 게 아니라 넓은 영역에 걸쳐 반응하고, 세 곡선이 <strong>크게 겹친다</strong>는 점이다. 그래서 원추세포 하나만으로는 색을 알 수 없다. 어떤 빛이 들어왔을 때 L·M·S가 각각 얼마나 반응했는가, 그 <strong>세 숫자의 비율</strong>이 색의 본질이다.",
                        "우리가 보는 수백만 가지 색은 결국 이 3차원 신호로 압축된다. 색이 본질적으로 '세 개의 숫자'라는 이 사실은, 다음 편에서 다룰 CIE 색좌표계가 왜 세 개의 <strong>삼자극치</strong>로 출발하는지의 뿌리이기도 하다."]),
            dict(h2="5. 세포 안에서 — 광전변환", fig="pt",
                 cap="광전변환 캐스케이드. 광자 한 알이 레티날의 모양을 바꾸고, 그 미세한 변화가 효소 연쇄로 크게 증폭되어 전기 신호가 된다.",
                 paras=["그렇다면 원추세포는 빛 한 알, 즉 <strong>광자</strong>를 어떻게 전기 신호로 바꿀까? 주인공은 <strong>옵신</strong>(opsin)이라는 단백질과 그 안에 박힌 <strong>레티날</strong>(retinal) 분자다.",
                        "평소 레티날은 '11-시스'라는 굽은 형태로 있다가, 광자를 흡수하는 순간 '올-트랜스'라는 펴진 형태로 바뀐다(이성질화). 이 미세한 모양 변화가 옵신을 활성화하고, 트랜스듀신 → PDE 효소 → cGMP 농도 급감으로 이어지는 연쇄 반응을 일으킨다. cGMP가 줄면 세포막의 이온 통로(CNG 채널)가 닫히고 세포는 <strong>과분극</strong>된다.",
                        "흥미로운 점은 빛이 신호를 '켜는' 게 아니라 <strong>'끄는'</strong> 방식이라는 것이다. 어두울 때 흐르던 전류가 빛을 받아 줄어들고, 바로 그 '변화'가 신호가 된다. 광자 한 알의 사건이 분자 캐스케이드를 통해 크게 증폭되어, 하나의 신경 신호로 태어난다."]),
            dict(h2="6. 시신경에서 대뇌피질까지", fig="path",
                 cap="망막에서 1차 시각피질(V1)까지의 경로. 도중에 L·M·S는 적-녹, 청-황, 명-암의 '차이' 신호로 다시 부호화된다(반대색 처리).",
                 paras=["원추·간상의 신호는 망막 안에서 양극세포·신경절세포를 거치며 1차 가공된다. 이때 L·M·S 값이 그대로 전달되는 게 아니라 <strong>'차이'로 재부호화</strong>된다 — 적-녹(L−M), 청-황(S 대 L+M), 그리고 명-암(L+M). 이 <strong>반대색</strong>(opponent) 구조 덕분에 우리는 '붉으면서 동시에 푸른 색' 같은 건 떠올리지 못한다.",
                        "신경절세포의 축삭은 다발을 이뤄 <strong>시신경</strong>이 되고, 시교차에서 좌우 정보가 재배열된 뒤 외측슬상핵(LGN)을 거쳐 뒤통수의 <strong>1차 시각피질(V1)</strong>에 도달한다. 뇌는 여기서부터 형태·움직임·색을 통합해 비로소 '본다'는 경험을 만든다.",
                        "결국 빨강은 바깥 세계에 있던 게 아니다. 빛이라는 물리량이 눈과 신경과 뇌를 거치며 합성해 낸, <strong>이 모든 과정의 끝에 놓인 결론</strong>이다."]),
        ],
        closing_h2="다음 편 — 색을 숫자로 만들다",
        closing="여기까지가 빛이 색 경험으로 바뀌는 메커니즘이다. 그런데 '내가 보는 빨강과 당신이 보는 빨강이 같은가'를 따지려면, 색을 말이 아니라 <strong>숫자</strong>로 정의해야 한다. 1931년, 인류는 처음으로 색을 정량화하는 좌표계를 세웠다. 다음 편에서는 그 <strong>CIE 1931</strong>이 어떤 실험에서 태어났는지, 색일치함수에 왜 <strong>음수</strong>가 등장하는지(가장 헷갈리는 지점), 그리고 더 균일한 CIE 1976·CIELAB·CIEDE2000으로 어떻게 발전했는지를 같은 깊이로 풀어낸다. <a href=\"/blog/color-science-02-color-in-numbers/\"><strong>→ 2부 읽기: 색을 숫자로 만들다</strong></a>",
        fig_word="그림",
        author_desc="색채과학·디스플레이 광학을 다루는 기술 해설. 본 글의 과학적 내용은 공개된 학술·교과서 자료에 근거하며, 도표는 모두 직접 제작했습니다.",
        src="참고: 인간 시각·색채과학의 표준 교과서 수준 내용(예: Wandell, <i>Foundations of Vision</i>; Stockman &amp; Sharpe의 원추 분광 감도; CIE 표준)을 바탕으로 재구성. 도표는 모두 오리지널 제작.",
        all_list="AI·테크 전체 목록", home="홈",
    )
    C["en"] = dict(
        title="The Science of Color ① How We See Color — From EM Waves to the Cortex",
        desc="How does light become 'color'? Electromagnetic waves, why visible light is visible, the eye's rods and cones, L/M/S cone phototransduction, and the path from optic nerve to cortex — an approachable color-science primer with original diagrams.",
        keywords="color science, color vision, electromagnetic spectrum, visible light, cone cells, rods, LMS, phototransduction, opsin, opponent process, visual cortex, display optics, lucky please",
        og_title="How We See Color — From EM Waves to the Cortex",
        og_desc="There is no wavelength called 'red'. The full path from physics to color experience, in original diagrams. The Science of Color, Part 1.",
        kicker="The Science of Color · Part 1", h1="How We See Color",
        sub="From electromagnetic waves to the visual cortex — how light becomes the experience we call 'color'",
        lead="Color is not paint smeared onto the outside world. There is no wavelength called 'red' anywhere out there. Color is an <strong>experience</strong>, built jointly by light as a physical phenomenon and by the eye, nerves, and brain that receive and interpret it. This article follows that first stage step by step: how light turns from a physical quantity into the experience of color.",
        secs=[
            dict(h2="1. Light, an electromagnetic wave", fig="em",
                 cap="The electromagnetic spectrum. Across a vast band from kilometre-long radio waves to gamma rays, the slice our eyes respond to is just 380–700nm.",
                 paras=["Light is a wave in which electric and magnetic fields push each other across space — an <strong>electromagnetic wave</strong>. Its wavelength (or frequency) sets its character: longer wavelength means lower energy, shorter means higher.",
                        "The spectrum is wider than intuition allows. It begins with radio waves kilometres long, passes through microwaves and infrared, crosses the narrow band we see, and continues into ultraviolet, X-rays, and gamma rays smaller than an atom. In that enormous spread, the slice the human eye responds to is roughly <strong>380nm to 700nm</strong> — barely a handful of its width."]),
            dict(h2="2. Why is visible light 'visible'?", fig="win",
                 cap="Solar radiation near 5800K (gold) peaks in the visible range, and the transmission of air and water (blue dashed) opens a 'window' over exactly that range. Visible light is where the two coincide.",
                 paras=["Why this particular narrow band? Not by chance, but where two physical facts overlap. First, the sunlight pouring onto Earth is close to 5800K blackbody radiation, and its intensity happens to <strong>peak</strong> in the visible range. Second, Earth's atmosphere and water block ultraviolet (via ozone) and absorb much of the infrared, yet open an almost transparent <strong>'window'</strong> across the visible band.",
                        "So this band is simply the light that reaches the surface most abundantly and most clearly. Life evolved its sensors to match the richest available signal. In other words, visible light is 'visible' not because the light is special, but because of <strong>how our eyes were built to fit it</strong>. If visible light were sound to a bat, to us it is color."]),
            dict(h2="3. The eye — where light arrives", fig="eye",
                 cap="Light passes the lens and forms an image on the retina. Of its two photoreceptors, rods handle brightness and night vision; cones handle color.",
                 paras=["Light passes through the cornea and lens and forms an image on the <strong>retina</strong>, the inner wall of the eye. The retina holds two kinds of photoreceptor that convert light into electrical signals.",
                        "<strong>Rods</strong> number about 120 million and are extraordinarily sensitive, handling dim light and contrast but not color — which is why the world looks grey at night. <strong>Cones</strong> number about 6 million, work in bright light, and create color. Cones are packed densely in the <strong>fovea</strong> at the center of vision, which is why things look sharpest and most colorful when you look straight at them."]),
            dict(h2="4. L, M, S — three channels", fig="lms",
                 cap="Spectral sensitivity of the L/M/S cones. Each responds over a broad range rather than a single wavelength, and the three curves overlap heavily. Color is the 'ratio' of these three responses.",
                 paras=["The starting point of color is, remarkably, just <strong>three kinds</strong> of cone. Each is most sensitive to long (L), medium (M), or short (S) wavelengths, with peaks near L 564nm, M 534nm, and S 420nm.",
                        "The key is that each cone does not sense a single wavelength but responds across a broad range, and the three curves <strong>overlap heavily</strong>. So a single cone can never tell you the color. When light arrives, how much each of L, M, and S responded — the <strong>ratio of those three numbers</strong> — is the essence of color.",
                        "The millions of colors we see all compress into this three-dimensional signal. That color is fundamentally 'three numbers' is also the root of why the CIE color system in Part 2 begins from three <strong>tristimulus values</strong>."]),
            dict(h2="5. Inside the cell — phototransduction", fig="pt",
                 cap="The phototransduction cascade. A single photon changes the shape of a retinal molecule, and that tiny change is amplified through an enzyme chain into an electrical signal.",
                 paras=["So how does a cone turn a single grain of light — a <strong>photon</strong> — into an electrical signal? The protagonists are a protein called <strong>opsin</strong> and the <strong>retinal</strong> molecule nested inside it.",
                        "Normally retinal sits in a bent shape called 11-cis; the instant it absorbs a photon it snaps to a straightened all-trans shape (isomerization). That tiny shape change activates opsin and triggers a chain: transducin → the enzyme PDE → a sharp fall in cGMP. As cGMP drops, ion channels (CNG channels) in the membrane close and the cell <strong>hyperpolarizes</strong>.",
                        "What is striking is that light does not switch the signal 'on' but <strong>'off'</strong>. A current that flowed in darkness is reduced by light, and that very 'change' becomes the signal. The event of a single photon is greatly amplified through a molecular cascade and born as one neural signal."]),
            dict(h2="6. From optic nerve to cortex", fig="path",
                 cap="The path from retina to primary visual cortex (V1). Along the way L/M/S are recoded into 'difference' signals: red–green, blue–yellow, light–dark (opponent processing).",
                 paras=["Cone and rod signals are first processed within the retina through bipolar and ganglion cells. Here the L/M/S values are not passed on as-is but <strong>recoded as 'differences'</strong> — red–green (L−M), blue–yellow (S vs L+M), and light–dark (L+M). This <strong>opponent</strong> structure is why we can never imagine a color that is 'reddish and bluish at the same time'.",
                        "The ganglion axons bundle into the <strong>optic nerve</strong>; at the optic chiasm the left and right information is rearranged, then relayed through the LGN to the <strong>primary visual cortex (V1)</strong> at the back of the head. From there the brain integrates form, motion, and color to finally create the experience of 'seeing'.",
                        "In the end, red was never out there in the world. It is a conclusion the brain synthesizes from a physical quantity as it passes through eye, nerve, and brain — <strong>the result at the very end of all this</strong>."]),
        ],
        closing_h2="Next — Turning Color into Numbers",
        closing="That is the mechanism by which light becomes the experience of color. But to ask whether 'the red I see is the same as the red you see', color must be defined not in words but in <strong>numbers</strong>. In 1931, humanity built the first coordinate system to quantify color. Part 2 unpacks, at the same depth, what experiment the <strong>CIE 1931</strong> was born from, why <strong>negative values</strong> appear in the color-matching functions (the most confusing point), and how it evolved toward the more uniform CIE 1976, CIELAB, and CIEDE2000. <a href=\"/blog/color-science-02-color-in-numbers-en/\"><strong>→ Read Part 2: Turning Color into Numbers</strong></a>",
        fig_word="Figure",
        author_desc="Technical explainers on color science and display optics. The scientific content here is based on public academic and textbook material; all diagrams are original.",
        src="Reconstructed from standard textbook-level material on human vision and color science (e.g. Wandell, <i>Foundations of Vision</i>; Stockman &amp; Sharpe cone fundamentals; CIE standards). All diagrams are original.",
        all_list="All AI &amp; Tech posts", home="Home",
    )
    C["ja"] = dict(
        title="色の科学① 私たちはどう色を見るか — 電磁波から大脳皮質まで",
        desc="光はどう「色」になるのか。電磁波、可視光が可視光である理由、眼の桿体・錐体、L・M・S錐体の光伝達、視神経から大脳皮質までを、自作の図でやさしく解説する色彩科学入門。",
        keywords="色彩科学, 色覚, 電磁波, 可視光, 錐体細胞, 桿体細胞, LMS, 光伝達, オプシン, 反対色, 視覚野, ディスプレイ光学, lucky please",
        og_title="私たちはどう色を見るか — 電磁波から大脳皮質まで",
        og_desc="「赤」という波長は存在しない。光が物理量から色の経験に変わる全過程を図解。色の科学・第1部。",
        kicker="色の科学 · 第1部", h1="私たちはどう色を見るか",
        sub="電磁波から大脳皮質まで — 光が「色」という経験に変わる全過程",
        lead="色は外界に塗られた絵の具ではない。「赤」という波長はどこにも存在しない。色とは、光という物理現象と、それを受けて解釈する眼・神経・脳が共につくり出す<strong>経験</strong>である。本稿はその第一段階、光が物理量から色の経験へと変わる過程を一歩ずつたどる。",
        secs=[
            dict(h2="1. 光という電磁波", fig="em",
                 cap="電磁波スペクトル。数kmの電波からガンマ線までの広大な帯の中で、眼が反応するのは380–700nmのごく一部だ。",
                 paras=["光は電場と磁場が互いを押し合いながら空間を進む波、すなわち<strong>電磁波</strong>である。波長(または振動数)がその性質を決める。波長が長ければエネルギーは低く、短ければ高い。",
                        "スペクトルは直感より遥かに広い。数kmの電波に始まり、マイクロ波・赤外線を経て、私たちが見る狭い帯を越え、紫外線・X線・原子より小さいガンマ線まで続く。その巨大な広がりの中で、人間の眼が反応するのはおよそ<strong>380nmから700nm</strong>、ほんの一握りの幅にすぎない。"]),
            dict(h2="2. 可視光はなぜ「可視」光なのか", fig="win",
                 cap="約5800Kの太陽放射(金)は可視域で強度が頂点を成し、大気・水の透過率(青破線)はまさにその域に「窓」を開く。可視光は両者が重なる場所だ。",
                 paras=["なぜこの狭い帯なのか。偶然ではなく、二つの物理的事実が重なった結果だ。第一に、地球に降り注ぐ太陽放射は約5800Kの黒体放射に近く、その強度はちょうど可視域で<strong>頂点</strong>を成す。第二に、地球の大気と水は紫外線をオゾンで遮り赤外線を大きく吸収する一方、可視域にはほぼ透明な<strong>「窓」</strong>を開く。",
                        "つまり地表に最も豊かに、最も鮮明に届く光がこの帯なのだ。生命は最も情報の豊かな信号に感覚器を合わせて進化した。言い換えれば可視光が「見える」のは光が特別だからではなく、<strong>その光に合わせて作られた私たちの眼の事情</strong>による。コウモリにとって可視光が音であるなら、私たちにとってそれは色だ。"]),
            dict(h2="3. 眼 — 光が届く場所", fig="eye",
                 cap="光は水晶体を経て網膜に結像する。二つの光受容体のうち桿体は明暗・暗所視を、錐体は色を担う。",
                 paras=["光は角膜と水晶体を通り、眼の内壁である<strong>網膜</strong>に像を結ぶ。網膜には光を電気信号へ変える光受容体が二種類ある。",
                        "<strong>桿体細胞</strong>は約1.2億個あり極めて敏感で、暗所と明暗を担うが色は区別できない。夜に世界が灰色に見えるのはそのためだ。<strong>錐体細胞</strong>は約600万個で明所で働き、色を生む。錐体は視野中心の<strong>中心窩</strong>に密集している。何かを「まっすぐ見る」とき最も鮮明で色豊かに見えるのはそのためだ。"]),
            dict(h2="4. L・M・S — 三つのチャネル", fig="lms",
                 cap="L・M・S錐体の分光感度。各細胞は単一波長ではなく広い範囲に反応し、三曲線は大きく重なる。色はこの三応答の「比」である。",
                 paras=["色の出発点は驚くほど僅か<strong>三種類</strong>の錐体だ。それぞれ長波長(L)・中波長(M)・短波長(S)に最も敏感で、感度の頂点はおよそL 564nm、M 534nm、S 420nm付近にある。",
                        "肝心なのは、各細胞が「単一波長」を捉えるのではなく広い範囲に反応し、三曲線が<strong>大きく重なる</strong>点だ。だから錐体一つでは色は分からない。ある光が入ったときL・M・Sがそれぞれどれだけ反応したか、その<strong>三数の比</strong>こそ色の本質である。",
                        "私たちが見る数百万の色は、結局この三次元の信号に圧縮される。色が本質的に「三つの数」であるこの事実は、第2部で扱うCIE表色系がなぜ三つの<strong>三刺激値</strong>から始まるのかの根でもある。"]),
            dict(h2="5. 細胞の中で — 光伝達", fig="pt",
                 cap="光伝達カスケード。光子一個がレチナールの形を変え、その微小な変化が酵素連鎖で大きく増幅されて電気信号になる。",
                 paras=["では錐体は光一粒、すなわち<strong>光子</strong>をどう電気信号に変えるのか。主役は<strong>オプシン</strong>というタンパク質と、その中に収まる<strong>レチナール</strong>分子だ。",
                        "普段レチナールは「11-シス」という曲がった形でいるが、光子を吸収した瞬間「オールトランス」という伸びた形に変わる(異性化)。この微小な形の変化がオプシンを活性化し、トランスデューシン→PDE酵素→cGMP濃度の急減へと続く連鎖を起こす。cGMPが減ると細胞膜のイオンチャネル(CNGチャネル)が閉じ、細胞は<strong>過分極</strong>する。",
                        "興味深いのは、光が信号を「オン」にするのではなく<strong>「オフ」</strong>にする点だ。暗所で流れていた電流が光で減り、まさにその「変化」が信号になる。光子一個の出来事が分子カスケードで大きく増幅され、一つの神経信号として生まれる。"]),
            dict(h2="6. 視神経から大脳皮質まで", fig="path",
                 cap="網膜から一次視覚野(V1)までの経路。途中でL・M・Sは赤-緑、青-黄、明-暗の「差」信号へ再符号化される(反対色処理)。",
                 paras=["錐体・桿体の信号は網膜内で双極細胞・神経節細胞を経て一次処理される。ここでL・M・S値はそのまま送られるのではなく<strong>「差」として再符号化</strong>される — 赤-緑(L−M)、青-黄(S対L+M)、そして明-暗(L+M)。この<strong>反対色</strong>構造のおかげで、私たちは「赤くて同時に青い色」を思い浮かべられない。",
                        "神経節細胞の軸索は束になり<strong>視神経</strong>となり、視交叉で左右の情報が再配置された後、外側膝状体(LGN)を経て後頭部の<strong>一次視覚野(V1)</strong>に達する。脳はここから形・動き・色を統合し、ようやく「見る」という経験をつくる。",
                        "結局、赤は外界にあったのではない。光という物理量が眼と神経と脳を経て合成した、<strong>この全過程の果てに置かれた結論</strong>なのだ。"]),
        ],
        closing_h2="次回 — 色を数にする",
        closing="ここまでが光が色の経験に変わる仕組みだ。だが「私の見る赤とあなたの見る赤は同じか」を問うには、色を言葉ではなく<strong>数</strong>で定義せねばならない。1931年、人類は初めて色を定量化する座標系を築いた。次回はその<strong>CIE 1931</strong>がどんな実験から生まれたか、色合わせ関数になぜ<strong>負の値</strong>が現れるのか(最も紛らわしい点)、そしてより均一なCIE 1976・CIELAB・CIEDE2000へどう発展したかを同じ深さで解く。 <a href=\"/blog/color-science-02-color-in-numbers-ja/\"><strong>→ 第2部を読む：色を数にする</strong></a>",
        fig_word="図",
        author_desc="色彩科学・ディスプレイ光学の技術解説。本稿の科学的内容は公開された学術・教科書資料に基づき、図はすべて自作。",
        src="人間視覚・色彩科学の標準的な教科書水準の内容(例: Wandell, <i>Foundations of Vision</i>; Stockman &amp; Sharpe の錐体分光感度; CIE標準)を基に再構成。図はすべてオリジナル制作。",
        all_list="AI・テック一覧", home="ホーム",
    )
    C["zh"] = dict(
        title="色彩的科学① 我们如何看见颜色 — 从电磁波到大脑皮层",
        desc="光如何变成「颜色」？电磁波、可见光为何可见、眼睛的视杆与视锥、L/M/S视锥的光转导、从视神经到大脑皮层 — 用原创图表通俗讲解的色彩科学入门。",
        keywords="色彩科学, 颜色视觉, 电磁波, 可见光, 视锥细胞, 视杆细胞, LMS, 光转导, 视蛋白, 对立色, 视觉皮层, 显示光学, lucky please",
        og_title="我们如何看见颜色 — 从电磁波到大脑皮层",
        og_desc="并不存在叫「红」的波长。光从物理量变为颜色经验的全过程图解。色彩的科学·第1部。",
        kicker="色彩的科学 · 第1部", h1="我们如何看见颜色",
        sub="从电磁波到视觉皮层 — 光如何变成我们称之为「颜色」的经验",
        lead="颜色不是涂在外部世界上的颜料。「红」这种波长在外界根本不存在。颜色是一种<strong>经验</strong>，由光这一物理现象，与接收并解释它的眼、神经、大脑共同造就。本文将一步步追踪这第一阶段：光如何从物理量变成颜色的经验。",
        secs=[
            dict(h2="1. 光，一种电磁波", fig="em",
                 cap="电磁波谱。从数公里长的无线电波到伽马射线的巨大波段中，眼睛能响应的只是380–700nm的极小一段。",
                 paras=["光是电场与磁场相互推动、穿越空间的波，即<strong>电磁波</strong>。波长(或频率)决定其性质：波长越长能量越低，越短则越高。",
                        "电磁波谱比直觉所及宽广得多。它始于数公里长的无线电波，经微波、红外，越过我们所见的狭窄波段，再延伸至紫外、X射线，乃至比原子还小的伽马射线。在这巨大的跨度中，人眼能响应的大约只是<strong>380nm到700nm</strong>，仅一小撮宽度。"]),
            dict(h2="2. 可见光为何「可见」", fig="win",
                 cap="约5800K的太阳辐射(金色)在可见区强度达到峰值，大气与水的透过率(蓝虚线)恰在该区开了一扇「窗」。可见光正是两者重叠之处。",
                 paras=["为何偏偏是这条窄带？并非偶然，而是两个物理事实的重叠。其一，倾泻到地球的太阳辐射接近5800K黑体辐射，其强度恰在可见区达到<strong>峰值</strong>。其二，地球的大气与水以臭氧阻挡紫外、大量吸收红外，却在可见区开了一扇近乎透明的<strong>「窗」</strong>。",
                        "也就是说，最丰沛、最清晰地抵达地表的光，正是这条波段。生命让感觉器官去匹配信息最丰富的信号而演化。换言之，可见光之所以「可见」，并非光本身特别，而在于<strong>我们的眼睛为适配它而生</strong>。若可见光于蝙蝠是声音，于我们便是颜色。"]),
            dict(h2="3. 眼睛 — 光抵达之处", fig="eye",
                 cap="光经晶状体在视网膜上成像。两种感光细胞中，视杆负责明暗与夜视，视锥负责颜色。",
                 paras=["光经过角膜与晶状体，在眼球内壁<strong>视网膜</strong>上成像。视网膜上有两类把光转为电信号的感光细胞。",
                        "<strong>视杆细胞</strong>约有1.2亿个，极其敏感，负责暗处与明暗，却无法分辨颜色 — 这正是夜里世界显得灰白的原因。<strong>视锥细胞</strong>约600万个，在明亮处工作并产生颜色。视锥密集分布于视野中心的<strong>中央凹</strong>，因此当你「直视」某物时，看到的最清晰、色彩最丰富。"]),
            dict(h2="4. L·M·S — 三个通道", fig="lms",
                 cap="L·M·S视锥的光谱灵敏度。每种细胞响应的是一段宽广范围而非单一波长，三条曲线大幅重叠。颜色是这三种响应的「比例」。",
                 paras=["颜色的起点，惊人地只是<strong>三种</strong>视锥。它们分别对长波(L)、中波(M)、短波(S)最敏感，灵敏度峰值约在L 564nm、M 534nm、S 420nm附近。",
                        "关键在于：每种细胞并非只感知单一波长，而是在宽广范围内响应，三条曲线<strong>大幅重叠</strong>。因此单凭一种视锥无法判断颜色。当光进入时，L·M·S各自响应了多少，这<strong>三个数的比例</strong>才是颜色的本质。",
                        "我们所见的数百万种颜色，最终都压缩进这个三维信号。颜色本质上是「三个数」这一事实，也正是第2部所述CIE表色系为何从三个<strong>三刺激值</strong>出发的根源。"]),
            dict(h2="5. 在细胞之内 — 光转导", fig="pt",
                 cap="光转导级联。一个光子改变视黄醛分子的形状，这一微小变化经酶链大幅放大，成为电信号。",
                 paras=["那么视锥如何把一粒光，即<strong>光子</strong>，变成电信号？主角是一种叫<strong>视蛋白</strong>(opsin)的蛋白质，以及嵌在其中的<strong>视黄醛</strong>(retinal)分子。",
                        "平时视黄醛处于「11-顺式」的弯曲形态，一旦吸收光子，瞬间变为「全反式」的伸展形态(异构化)。这一微小的形状变化激活视蛋白，触发转导蛋白→PDE酶→cGMP浓度骤降的连锁反应。cGMP减少时，细胞膜上的离子通道(CNG通道)关闭，细胞发生<strong>超极化</strong>。",
                        "有趣的是，光并非把信号「打开」，而是把它<strong>「关闭」</strong>。暗处流动的电流因光而减少，正是这一「变化」成为信号。一个光子的事件经分子级联被大幅放大，诞生为一束神经信号。"]),
            dict(h2="6. 从视神经到大脑皮层", fig="path",
                 cap="从视网膜到初级视觉皮层(V1)的通路。途中L·M·S被重新编码为红-绿、蓝-黄、明-暗的「差值」信号(对立色处理)。",
                 paras=["视锥与视杆的信号先在视网膜内经双极细胞、神经节细胞做初级处理。此处L·M·S值并非原样传递，而是<strong>重新编码为「差值」</strong> — 红-绿(L−M)、蓝-黄(S对L+M)、以及明-暗(L+M)。正因这种<strong>对立色</strong>结构，我们无法想象「既红又蓝」的颜色。",
                        "神经节细胞的轴突束成<strong>视神经</strong>，在视交叉处左右信息被重排，再经外侧膝状体(LGN)抵达后脑的<strong>初级视觉皮层(V1)</strong>。大脑自此整合形状、运动与颜色，才最终造出「看见」的经验。",
                        "归根结底，红从不在外部世界。它是光这一物理量经过眼、神经与大脑合成而来，<strong>置于这一切尽头的结论</strong>。"]),
        ],
        closing_h2="下一部 — 把颜色变成数字",
        closing="以上便是光变为颜色经验的机制。但要追问「我看到的红与你看到的红是否相同」，就必须用<strong>数字</strong>而非语言来定义颜色。1931年，人类首次建立了量化颜色的坐标系。下一部将以同样的深度，解读<strong>CIE 1931</strong>诞生于怎样的实验，颜色匹配函数中为何出现<strong>负值</strong>(最易混淆之处)，以及它如何演进到更均匀的CIE 1976、CIELAB与CIEDE2000。 <a href=\"/blog/color-science-02-color-in-numbers-zh/\"><strong>→ 阅读第2部：把颜色变成数字</strong></a>",
        fig_word="图",
        author_desc="色彩科学与显示光学的技术解说。本文科学内容基于公开的学术与教科书资料，图表均为原创制作。",
        src="基于人类视觉与色彩科学的标准教科书级内容(如 Wandell, <i>Foundations of Vision</i>；Stockman &amp; Sharpe 视锥基础函数；CIE 标准)重构。图表均为原创。",
        all_list="全部 AI·科技文章", home="首页",
    )
    return C[lang]
