# -*- coding: utf-8 -*-
"""Prose content (ko/en/ja/zh) for Color Science Part 2 — Turning Color into
Numbers (CIE 1931 -> CMF negatives -> XYZ -> chromaticity -> MacAdam ->
CIE 1976 u'v' / CIELAB -> CIEDE2000). Display formulas are inserted by the
generator (language-neutral), referenced here as 'fml' keys per section."""


def content(lang):
    C = {}
    C["ko"] = dict(
        title="색의 과학 ② 색을 숫자로 만들다 — CIE 1931에서 CIEDE2000까지",
        desc="색을 어떻게 숫자로 정의했나. 색일치 실험, 색일치함수에 음수가 나오는 이유, 가상 원색 X·Y·Z, CIE 1931 말굽 색도도, 맥아담 타원과 비균일성, CIE 1976 u'v'·CIELAB, 그리고 색차 ΔE와 CIEDE2000을 도표로 풀어낸 색채과학 2부.",
        keywords="CIE 1931, 색일치함수, 색좌표, 삼자극치, XYZ, 색도도, 맥아담 타원, CIELAB, CIE 1976, CIEDE2000, 색차, 델타E, 색역, 디스플레이 색재현, lucky please",
        og_title="색을 숫자로 만들다 — CIE 1931에서 CIEDE2000까지",
        og_desc="색일치함수는 왜 음수가 나올까. 인류가 색을 정량화한 한 세기의 과정을 도표로. 색의 과학 2부.",
        kicker="색의 과학 · 2부", h1="색을 숫자로 만들다",
        sub="CIE 1931에서 CIEDE2000까지 — 인류가 색을 측정하고 좌표로 묶은 한 세기",
        lead="1부에서 우리는 색이 결국 L·M·S 세 숫자의 <strong>비율</strong>임을 보았다. 하지만 '내가 보는 빨강'을 남에게 정확히 전하려면, 느낌이 아니라 누구나 같은 값을 얻는 <strong>표준 좌표</strong>가 필요하다. 1931년 국제조명위원회(CIE)는 사람을 직접 실험대에 앉혀 색을 측정했고, 그 결과는 오늘날 모든 디스플레이·카메라·인쇄의 바탕이 되었다.",
        secs=[
            dict(h2="1. 색을 재는 실험 — 색일치", fig="match",
                 cap="색일치 실험. 화면을 반으로 나눠 한쪽엔 측정할 단색광을, 다른 쪽엔 세 기준광(R 700·G 546·B 436nm)을 섞어 비추고, 두 반쪽이 같아 보일 때까지 손잡이를 돌린다.",
                 paras=["방법은 의외로 단순하고 아름답다. 둥근 화면을 반으로 나눠, 한쪽엔 측정하려는 <strong>단색광</strong>(특정 파장 하나)을 비춘다. 다른 쪽엔 세 개의 기준광, 빨강(700nm)·초록(546.1nm)·파랑(435.8nm)을 섞어 비춘다.",
                        "관찰자는 세 기준광의 밝기 손잡이를 돌려 두 반쪽이 <strong>똑같아 보이게</strong> 맞춘다. 일치한 순간의 세 값 R·G·B가 그 파장의 색을 '세 원색으로 표현한 좌표'다. 모든 가시 파장에 대해 이 실험을 반복하면, 파장마다 필요한 R·G·B 양을 나타내는 세 곡선이 나온다."]),
            dict(h2="2. 색일치함수 r̄ ḡ b̄", fig="cmf_rgb",
                 cap="CIE RGB 색일치함수. 각 파장의 단색광을 만드는 데 필요한 R·G·B의 양. r̄(λ)의 약 440–545nm 구간이 0 아래, 즉 음수로 내려간다.",
                 paras=["이 세 곡선이 <strong>색일치함수</strong>(color matching function)다. r̄(λ)·ḡ(λ)·b̄(λ)는 각 파장의 단색광을 재현하려면 R·G·B가 얼마나 필요한지 알려준다. 임의의 빛에 대한 색은 이 함수로 적분해 얻는다.",
                        "그런데 곡선을 처음 보면 이상한 점이 눈에 띈다. <strong>r̄(λ)의 일부 구간이 0 아래, 즉 음수로 내려간다.</strong> 빛을 '음수만큼' 더한다는 게 대체 무슨 뜻일까. 색일치를 배울 때 누구나 여기서 멈칫한다."]),
            dict(h2="3. 왜 음수가 나오는가", fig="negative",
                 cap="음수의 정체. 진한 청록(≈500nm)은 R·G·B를 더해서는 만들 수 없다. 그래서 빨강을 '측정 색 쪽'에 더해 탁하게 만든 뒤 일치시킨다 — 식에서는 빨강을 뺀 것(−R)이 되어 음수로 기록된다.",
                 paras=["핵심은 이렇다. 어떤 청록색(약 500nm) 단색광은 너무 순수하고 진해서, 빨강·초록·파랑을 아무리 더해도 그만큼 진한 청록이 나오지 않는다. 섞을수록 <strong>탁해질</strong> 뿐이다.",
                        "그래서 실험자는 발상을 뒤집는다. 기준광 쪽이 아니라, 측정하려는 <strong>청록색 쪽에 빨강을 조금 더해</strong> 그 청록을 살짝 탁하게 만든 뒤, 남은 초록+파랑과 일치시킨다. 식으로 옮기면 '측정 색 + 빨강 = 초록 + 파랑', 즉 '측정 색 = 초록 + 파랑 − 빨강'이 된다. 이 <strong>빼준 빨강</strong>이 바로 음수 r̄다.",
                        "다시 말해 음수는 '거꾸로 더한 빛'의 기록이다. 물리적으로 빛을 빼는 게 아니라, <strong>빼야만 일치하는 색이 존재한다</strong>는 인간 색각의 한계가 숫자에 새겨진 것이다. 실재하는 세 원색만으로는 모든 색을 '양수로' 표현할 수 없다는 뜻이기도 하다."]),
            dict(h2="4. 음수를 없앤 X·Y·Z", fig="xyz_cmf",
                 cap="CIE 1931 XYZ 색일치함수. 가상 원색 X·Y·Z로 다시 쓰면 세 함수가 전 구간 양수가 된다. ȳ(λ)는 사람이 느끼는 밝기(광도)와 일치하도록 설계됐다.",
                 paras=["음수는 계산에 불편했다. 그래서 CIE는 영리한 수학적 변환을 했다. 실제로는 존재하지 않는 세 개의 <strong>가상 원색</strong> X·Y·Z를 정의한 것이다. 이들은 어떤 실재하는 빛보다도 진한, 물리적으로 만들 수 없는 색이지만 좌표로서는 완벽히 작동한다.",
                        "이 가상 원색으로 다시 쓰면 모든 색일치함수 x̄·ȳ·z̄가 <strong>전 구간 양수</strong>가 된다. 게다가 ȳ(λ)는 사람이 느끼는 밝기(광도)와 일치하도록 설계되어, Y값 하나가 곧 밝기가 된다.",
                        "임의의 빛 S(λ)에 대한 좌표는 아래처럼 적분해 세 숫자 X·Y·Z, 곧 <strong>삼자극치</strong>를 얻는다. 1부의 'L·M·S 세 숫자'가 여기서 X·Y·Z 세 숫자로 표준화된 셈이다."],
                 fml=["xyz_int"]),
            dict(h2="5. CIE 1931 색좌표 — 말굽", fig="chromaticity",
                 cap="CIE 1931 xy 색도도. 바깥 곡선은 순수 단색광(스펙트럼 궤적), 아래 직선은 보라선, 안쪽은 백색점. 실재하는 모든 색이 이 말굽 안에 들어간다. 디스플레이 색역은 그 안의 삼각형이다.",
                 paras=["삼자극치 X·Y·Z는 3차원이라 종이에 그리기 불편하다. 그래서 밝기를 떼어내고 '색상·채도'만 2차원으로 투영한다(아래 식). 이 (x,y) 평면이 그 유명한 <strong>말굽 모양</strong> 색도도다.",
                        "바깥 곡선은 순수 단색광인 <strong>스펙트럼 궤적</strong>, 아래 직선은 빨강과 파랑을 잇는 보라선, 안쪽 중앙은 백색점이다. 실재하는 모든 색은 이 말굽 안에 들어간다. 디스플레이가 표현하는 색 범위(<strong>색역, gamut</strong>)는 이 안의 삼각형으로 그려진다 — sRGB, DCI-P3, BT.2020이 점점 커지는 삼각형이다."],
                 fml=["xy"]),
            dict(h2="6. 1931의 한계 — 균일하지 않다", fig="macadam",
                 cap="맥아담 타원(개념도). '겨우 구분되는 색 차이'의 경계가 위치마다 크기·방향이 제각각이다. 초록에선 거대하고(둔감) 파랑에선 작다(민감). 거리 ≠ 체감 차이.",
                 paras=["CIE 1931은 혁명이었지만 한 가지 약점이 있다. 색도도 위에서 <strong>같은 거리가 같은 '색 차이'를 뜻하지 않는다</strong>는 것이다.",
                        "1942년 맥아담(MacAdam)은 사람이 '차이를 겨우 느끼는' 경계를 측정했는데, 그 경계가 작은 타원으로 나타났다. 문제는 이 타원들의 크기와 방향이 위치마다 제각각이라는 것 — 초록 영역에선 거대하고(둔감), 파랑 영역에선 작다(민감). 즉 좌표상 두 색의 거리를 재도, 그게 사람이 느끼는 차이와 비례하지 않는다.",
                        "색을 '<strong>관리</strong>'하려면 — 예컨대 두 패널의 색이 충분히 가까운가를 한 숫자로 판정하려면 — 거리=차이가 성립하는 더 균일한 좌표가 필요했다."]),
            dict(h2="7. 더 균일하게 — CIE 1976 u'v'와 CIELAB", fig="lab",
                 cap="CIELAB 색공간. L*은 밝기(0~100), a*는 녹(−)↔적(+), b*는 청(−)↔황(+). 1부에서 본 반대색 구조를 그대로 좌표축으로 옮겼다. 두 색의 차이는 이제 두 점 사이 거리다.",
                 paras=["첫 보정은 좌표를 비선형으로 다시 늘려 맥아담 타원을 최대한 <strong>원</strong>에 가깝게 만드는 것이었다. 그렇게 나온 게 CIE 1976 UCS, u'·v' 색도도다(아래 식). 타원들이 훨씬 고르게 펴진다.",
                        "같은 해 CIE는 한 발 더 나아가 밝기까지 포함한 3차원 균일 색공간 <strong>CIELAB(L*a*b*)</strong>을 정의했다. L*은 밝기(0 검정~100 흰색), a*는 녹(−)↔적(+), b*는 청(−)↔황(+) 축으로, 1부에서 본 <strong>반대색</strong> 구조를 그대로 좌표로 옮긴 것이다.",
                        "변환은 XYZ를 기준 백색으로 나눈 뒤 세제곱근 꼴 함수를 거친다. 핵심 효과는 단순하다. 이제 두 색의 차이를 <strong>그냥 두 점 사이 거리</strong>로 잴 수 있게 됐다."],
                 fml=["uv", "lab"]),
            dict(h2="8. 색차의 완성 — ΔE76에서 CIEDE2000", fig="de",
                 cap="색차 ΔE의 진화. ΔE76은 단순한 유클리드 거리. CIEDE2000은 밝기·채도·색상에 가중치(SL·SC·SH)와 파랑 영역 보정(회전항 RT)을 더해 체감 차이에 맞춘다.",
                 paras=["CIELAB에서 두 색의 차이는 유클리드 거리, ΔE*ab다(아래 식, 1976). 직관적이고 오래 쓰였지만, CIELAB조차 완벽히 균일하진 않아 특히 <strong>파랑·고채도</strong> 영역에서 사람 느낌과 어긋났다.",
                        "그래서 1994년, 이어 2000년 보정식이 나왔다. 현재 산업 표준인 <strong>CIEDE2000(ΔE00)</strong>은 밝기·채도·색상 차이에 각각 가중치(SL·SC·SH)를 주고, 채도가 높을수록 차이를 덜 세게 보며, 파랑 영역의 색상-채도 상호작용을 잡는 <strong>회전항(RT)</strong>까지 더한다.",
                        "식은 길고 복잡하지만 목적은 하나다 — 계산한 ΔE 한 숫자가 사람이 실제로 느끼는 색 차이와 최대한 맞아떨어지게 만드는 것. ΔE00이 약 1이면 훈련된 눈이 겨우 구분하는 차이이고, 그게 오늘날 디스플레이·인쇄·도료의 <strong>품질 기준</strong>이 된다."],
                 fml=["de76", "de00"]),
        ],
        closing_h2="두 편을 마치며",
        closing="1부가 '눈이 색을 만드는' 생물학이었다면, 2부는 '그 색을 모두가 공유하는 숫자로 묶은' 표준의 역사였다. L·M·S 세 원추에서 시작해 X·Y·Z 삼자극치, 말굽 색도도, 그리고 CIEDE2000까지 — 우리가 매일 보는 화면의 색이 '정확하다'고 말할 수 있는 건 이 한 세기의 측정 덕분이다. 실제 디스플레이에서 이 좌표가 색역·캘리브레이션·색관리로 어떻게 쓰이는지는 다음 기회에 다룬다.",
        fig_word="그림",
        prev_label="← 1부", prev_text="우리는 어떻게 색을 보는가",
        author_desc="색채과학·디스플레이 광학을 다루는 기술 해설. 본 글의 과학적 내용은 공개된 학술·표준(CIE) 자료에 근거하며, 도표는 모두 직접 제작했습니다.",
        src="참고: CIE 표준(CIE 15, 색도/색차), 인간 시각·색채과학의 표준 교과서 수준 내용을 바탕으로 재구성. XYZ 색일치함수는 공개된 해석적 근사식으로 계산. 도표는 모두 오리지널 제작.",
        all_list="AI·테크 전체 목록", home="홈",
    )
    C["en"] = dict(
        title="The Science of Color ② Turning Color into Numbers — CIE 1931 to CIEDE2000",
        desc="How color was defined in numbers: the color-matching experiment, why the matching functions go negative, the imaginary primaries X/Y/Z, the CIE 1931 horseshoe, MacAdam ellipses and non-uniformity, CIE 1976 u'v' / CIELAB, and color difference ΔE to CIEDE2000 — Part 2 in diagrams.",
        keywords="CIE 1931, color matching functions, chromaticity, tristimulus, XYZ, color diagram, MacAdam ellipses, CIELAB, CIE 1976, CIEDE2000, color difference, delta E, gamut, display color, lucky please",
        og_title="Turning Color into Numbers — CIE 1931 to CIEDE2000",
        og_desc="Why do the color-matching functions go negative? A century of quantifying color, in diagrams. The Science of Color, Part 2.",
        kicker="The Science of Color · Part 2", h1="Turning Color into Numbers",
        sub="From CIE 1931 to CIEDE2000 — the century in which humanity measured color and pinned it to coordinates",
        lead="In Part 1 we saw that color is, in the end, the <strong>ratio</strong> of three numbers, L, M, S. But to convey 'the red I see' to someone else precisely, you need not a feeling but a <strong>standard coordinate</strong> everyone can reproduce. In 1931 the International Commission on Illumination (CIE) sat people at a bench and measured color, and the result became the basis of every display, camera, and print today.",
        secs=[
            dict(h2="1. Measuring color — color matching", fig="match",
                 cap="The color-matching experiment. A field is split: one half shows a monochromatic test light, the other a mix of three primaries (R 700, G 546, B 436nm). The observer turns the knobs until the two halves look identical.",
                 paras=["The method is surprisingly simple and beautiful. A round field is split in two: one half is lit by the <strong>monochromatic light</strong> being measured (a single wavelength). The other half is lit by a mix of three primaries — red (700nm), green (546.1nm), blue (435.8nm).",
                        "The observer turns the brightness knobs of the three primaries until the two halves look <strong>identical</strong>. The three values R, G, B at the match are that wavelength's color expressed as 'coordinates in three primaries'. Repeat across every visible wavelength and you get three curves: how much R, G, B each wavelength needs."]),
            dict(h2="2. The color-matching functions r̄ ḡ b̄", fig="cmf_rgb",
                 cap="The CIE RGB color-matching functions — how much R, G, B each wavelength needs. Notice that r̄(λ) dips below zero, going negative, roughly between 440–545nm.",
                 paras=["These three curves are the <strong>color-matching functions</strong>. r̄(λ), ḡ(λ), b̄(λ) tell you how much R, G, B is needed to reproduce each wavelength. The color of any light is obtained by integrating against them.",
                        "But on first sight something looks odd. <strong>Part of r̄(λ) dips below zero — it goes negative.</strong> What on earth does it mean to add a 'negative amount' of light? Everyone learning color matching pauses here."]),
            dict(h2="3. Why does it go negative?", fig="negative",
                 cap="The meaning of negative. A saturated cyan (≈500nm) cannot be made by adding R, G, B. So red is added to the test side to dull it, then matched — in the equation that red appears subtracted (−R), recorded as negative.",
                 paras=["Here is the key. A certain cyan (around 500nm) monochromatic light is so pure and saturated that no amount of red, green, and blue added together can reach it. Mixing only makes it <strong>duller</strong>.",
                        "So the experimenter flips the idea. Instead of the primary side, they add <strong>a little red to the cyan test light itself</strong>, slightly dulling it, then match it with the remaining green + blue. As an equation: 'test + red = green + blue', i.e. 'test = green + blue − red'. That <strong>subtracted red</strong> is exactly the negative r̄.",
                        "In other words, the negative is the record of 'light added to the other side'. Nothing physically subtracts light; rather, the limit of human color vision — that <strong>some colors can only be matched by subtracting</strong> — is written into the numbers. It also means no three real primaries can express every color with positive amounts alone."]),
            dict(h2="4. X, Y, Z — removing the negatives", fig="xyz_cmf",
                 cap="The CIE 1931 XYZ color-matching functions. Rewritten in the imaginary primaries X, Y, Z, all three functions are positive everywhere. ȳ(λ) is designed to match perceived brightness (luminance).",
                 paras=["Negatives were inconvenient for calculation, so the CIE made a clever transform: it defined three <strong>imaginary primaries</strong> X, Y, Z that do not physically exist. They are more saturated than any real light, impossible to produce, yet they work perfectly as coordinates.",
                        "Rewritten in these primaries, all the matching functions x̄, ȳ, z̄ are <strong>positive everywhere</strong>. Better still, ȳ(λ) is designed to match perceived brightness, so the single value Y is luminance.",
                        "For any light S(λ), integrating as below yields three numbers X, Y, Z — the <strong>tristimulus values</strong>. The 'three numbers L, M, S' of Part 1 are here standardized into three numbers X, Y, Z."],
                 fml=["xyz_int"]),
            dict(h2="5. The CIE 1931 chromaticity diagram — the horseshoe", fig="chromaticity",
                 cap="The CIE 1931 xy diagram. The outer curve is pure monochromatic light (the spectral locus), the bottom line is the purple line, the center is the white point. Every real color lies inside. A display's gamut is a triangle within it.",
                 paras=["Tristimulus X, Y, Z are three-dimensional, awkward to draw on paper. So we strip out brightness and project just 'hue and saturation' into 2D (formula below). That (x, y) plane is the famous <strong>horseshoe</strong> diagram.",
                        "The outer curve is pure monochromatic light, the <strong>spectral locus</strong>; the bottom straight line is the purple line joining red and blue; the center is the white point. Every real color falls inside this horseshoe. A display's color range (its <strong>gamut</strong>) is drawn as a triangle within it — sRGB, DCI-P3, BT.2020 are ever-larger triangles."],
                 fml=["xy"]),
            dict(h2="6. The limit of 1931 — it isn't uniform", fig="macadam",
                 cap="MacAdam ellipses (schematic). The boundary of 'just-noticeable' color difference varies wildly in size and orientation by location — huge in green (insensitive), tiny in blue (sensitive). Distance ≠ perceived difference.",
                 paras=["CIE 1931 was a revolution, but it has one weakness: on the diagram, <strong>equal distances do not mean equal 'color differences'</strong>.",
                        "In 1942 MacAdam measured the boundary at which people can 'just barely notice' a difference, and it came out as small ellipses. The problem is that the size and orientation of these ellipses vary by location — enormous in the green region (insensitive), tiny in blue (sensitive). So measuring the distance between two colors on the diagram does not track what people actually perceive.",
                        "To <strong>manage</strong> color — to judge with a single number whether two panels are close enough, say — you needed a more uniform coordinate where distance equals difference."]),
            dict(h2="7. More uniform — CIE 1976 u'v' and CIELAB", fig="lab",
                 cap="The CIELAB color space. L* is lightness (0–100), a* runs green(−)↔red(+), b* blue(−)↔yellow(+). The opponent structure from Part 1, turned straight into axes. Color difference is now just the distance between two points.",
                 paras=["The first fix was to nonlinearly re-stretch the coordinates so the MacAdam ellipses become as close to <strong>circles</strong> as possible. That gave the CIE 1976 UCS, the u'v' diagram (formula below); the ellipses spread out far more evenly.",
                        "The same year the CIE went further and defined a 3D uniform color space including lightness, <strong>CIELAB (L*a*b*)</strong>. L* is lightness (0 black to 100 white), a* runs green(−)↔red(+), b* blue(−)↔yellow(+) — the <strong>opponent</strong> structure from Part 1, turned directly into axes.",
                        "The transform divides XYZ by a reference white, then passes it through a cube-root-like function. The key effect is simple: color difference can now be measured as <strong>just the distance between two points</strong>."],
                 fml=["uv", "lab"]),
            dict(h2="8. Completing color difference — ΔE76 to CIEDE2000", fig="de",
                 cap="The evolution of color difference ΔE. ΔE76 is a plain Euclidean distance; CIEDE2000 adds weights for lightness/chroma/hue (SL·SC·SH) and a blue-region correction (the rotation term RT) to fit perception.",
                 paras=["In CIELAB the difference between two colors is a Euclidean distance, ΔE*ab (formula below, 1976). Intuitive and long used, but CIELAB is not perfectly uniform either, diverging from perception especially in the <strong>blue and high-chroma</strong> regions.",
                        "So corrections came in 1994 and then 2000. The current industry standard, <strong>CIEDE2000 (ΔE00)</strong>, weights lightness, chroma, and hue differences separately (SL, SC, SH), discounts differences more at high chroma, and adds a <strong>rotation term (RT)</strong> to capture the hue–chroma interaction in the blue region.",
                        "The formula is long and complex, but its goal is one thing: to make the single computed ΔE match what people actually perceive. A ΔE00 of about 1 is a difference a trained eye can barely tell apart — and that is the <strong>quality bar</strong> for displays, print, and paint today."],
                 fml=["de76", "de00"]),
        ],
        closing_h2="Closing the two parts",
        closing="If Part 1 was the biology of 'the eye making color', Part 2 was the history of the standard that 'pinned that color to numbers everyone shares'. From three cones L, M, S to the tristimulus X, Y, Z, the horseshoe diagram, and CIEDE2000 — the reason we can call the color on our screens 'accurate' is this century of measurement. How these coordinates are used in real displays, for gamut, calibration, and color management, is for another time.",
        fig_word="Figure",
        prev_label="← Part 1", prev_text="How We See Color",
        author_desc="Technical explainers on color science and display optics. The scientific content is based on public academic and standards (CIE) material; all diagrams are original.",
        src="Reconstructed from CIE standards (CIE 15, colorimetry/color difference) and standard textbook-level material on human vision and color science. The XYZ color-matching functions are computed from a published analytic approximation. All diagrams are original.",
        all_list="All AI &amp; Tech posts", home="Home",
    )
    C["ja"] = dict(
        title="色の科学② 色を数にする — CIE 1931からCIEDE2000まで",
        desc="色をどう数で定義したか。色合わせ実験、等色関数に負の値が出る理由、仮想原色X・Y・Z、CIE 1931馬蹄形色度図、マクアダム楕円と非均一性、CIE 1976 u'v'・CIELAB、色差ΔEとCIEDE2000を図解する色彩科学・第2部。",
        keywords="CIE 1931, 等色関数, 色度図, 三刺激値, XYZ, マクアダム楕円, CIELAB, CIE 1976, CIEDE2000, 色差, デルタE, 色域, ディスプレイ色再現, lucky please",
        og_title="色を数にする — CIE 1931からCIEDE2000まで",
        og_desc="等色関数はなぜ負になるのか。人類が色を定量化した一世紀を図解。色の科学・第2部。",
        kicker="色の科学 · 第2部", h1="色を数にする",
        sub="CIE 1931からCIEDE2000まで — 人類が色を測り座標に結びつけた一世紀",
        lead="第1部で私たちは、色が結局L・M・S三つの数の<strong>比</strong>であることを見た。だが「私の見る赤」を他人に正確に伝えるには、感覚ではなく誰もが同じ値を得る<strong>標準座標</strong>が要る。1931年、国際照明委員会(CIE)は人を実験台に座らせて色を測り、その結果は今日のあらゆるディスプレイ・カメラ・印刷の土台になった。",
        secs=[
            dict(h2="1. 色を測る実験 — 等色", fig="match",
                 cap="等色実験。視野を半分に分け、片側に測る単色光を、もう片側に三原色(R 700・G 546・B 436nm)を混ぜて当て、両半分が同じに見えるまでつまみを回す。",
                 paras=["方法は意外に単純で美しい。円い視野を半分に分け、片側に測りたい<strong>単色光</strong>(一つの波長)を当てる。もう片側には三つの原色、赤(700nm)・緑(546.1nm)・青(435.8nm)を混ぜて当てる。",
                        "観察者は三原色の明るさのつまみを回し、両半分が<strong>同じに見える</strong>よう合わせる。一致した瞬間の三値R・G・Bが、その波長の色を「三原色で表した座標」だ。すべての可視波長で繰り返すと、波長ごとに必要なR・G・Bの量を表す三本の曲線が得られる。"]),
            dict(h2="2. 等色関数 r̄ ḡ b̄", fig="cmf_rgb",
                 cap="CIE RGB等色関数。各波長の単色光を作るのに必要なR・G・Bの量。r̄(λ)が約440–545nmで0を下回り、負になる。",
                 paras=["この三本の曲線が<strong>等色関数</strong>だ。r̄(λ)・ḡ(λ)・b̄(λ)は各波長の単色光を再現するのにR・G・Bがどれだけ要るかを示す。任意の光の色はこれで積分して得る。",
                        "ところが曲線を初めて見ると妙な点に気づく。<strong>r̄(λ)の一部が0を下回り、負になる。</strong>光を「負の量」加えるとは一体どういうことか。等色を学ぶ誰もがここで立ち止まる。"]),
            dict(h2="3. なぜ負になるのか", fig="negative",
                 cap="負の正体。濃いシアン(≈500nm)はR・G・Bを足しても作れない。だから赤を「測る色の側」に足して濁らせてから一致させる — 式では赤を引いた(−R)形になり、負として記録される。",
                 paras=["核心はこうだ。あるシアン(約500nm)の単色光は純粋で濃すぎて、赤・緑・青をいくら足してもそこまで濃いシアンにならない。混ぜるほど<strong>濁る</strong>だけだ。",
                        "そこで実験者は発想を逆転する。原色側ではなく、測りたい<strong>シアンの側に赤を少し足し</strong>て濁らせ、残る緑+青と一致させる。式にすると「測る色 + 赤 = 緑 + 青」、つまり「測る色 = 緑 + 青 − 赤」。この<strong>引いた赤</strong>こそ負のr̄だ。",
                        "つまり負は「逆側に足した光」の記録だ。物理的に光を引くのではなく、<strong>引かねば一致しない色がある</strong>という人間の色覚の限界が数に刻まれたのだ。実在する三原色だけでは、あらゆる色を「正の量」で表せないことも意味する。"]),
            dict(h2="4. 負を消したX・Y・Z", fig="xyz_cmf",
                 cap="CIE 1931 XYZ等色関数。仮想原色X・Y・Zで書き直すと三関数が全域で正になる。ȳ(λ)は人が感じる明るさ(光度)に一致するよう設計されている。",
                 paras=["負は計算に不便だった。そこでCIEは巧みな変換をした。実在しない三つの<strong>仮想原色</strong>X・Y・Zを定義したのだ。これらはどんな実在の光より濃い、物理的に作れない色だが、座標としては完璧に働く。",
                        "この原色で書き直すと、等色関数x̄・ȳ・z̄はすべて<strong>全域で正</strong>になる。さらにȳ(λ)は人の感じる明るさに一致するよう設計され、Y値一つが光度になる。",
                        "任意の光S(λ)に対し、下のように積分して三つの数X・Y・Z、すなわち<strong>三刺激値</strong>を得る。第1部の「L・M・S三つの数」がここでX・Y・Z三つの数に標準化されたわけだ。"],
                 fml=["xyz_int"]),
            dict(h2="5. CIE 1931色度図 — 馬蹄形", fig="chromaticity",
                 cap="CIE 1931 xy色度図。外側の曲線は純粋な単色光(スペクトル軌跡)、下の直線は純紫軌跡、中心は白色点。実在する全ての色がこの馬蹄形の内に入る。ディスプレイの色域はその中の三角形だ。",
                 paras=["三刺激値X・Y・Zは三次元で紙に描きにくい。そこで明るさを外し、「色相・彩度」だけを2次元に投影する(下の式)。その(x, y)平面が有名な<strong>馬蹄形</strong>の色度図だ。",
                        "外側の曲線は純粋な単色光の<strong>スペクトル軌跡</strong>、下の直線は赤と青を結ぶ純紫軌跡、中心は白色点。実在する全ての色がこの馬蹄形の内に収まる。ディスプレイの色の範囲(<strong>色域, gamut</strong>)はその中の三角形で描かれる — sRGB、DCI-P3、BT.2020と次第に大きな三角形になる。"],
                 fml=["xy"]),
            dict(h2="6. 1931の限界 — 均一ではない", fig="macadam",
                 cap="マクアダム楕円(概念図)。「ようやく気づく色差」の境界が、位置ごとに大きさも向きもばらばら。緑で巨大(鈍感)、青で小さい(敏感)。距離 ≠ 体感差。",
                 paras=["CIE 1931は革命だったが一つ弱点がある。色度図上で<strong>同じ距離が同じ「色差」を意味しない</strong>のだ。",
                        "1942年マクアダムは人が「ようやく差に気づく」境界を測り、それは小さな楕円として現れた。問題はこの楕円の大きさと向きが位置ごとにばらばらなこと — 緑の領域では巨大(鈍感)、青では小さい(敏感)。座標上で二色の距離を測っても、人の感じる差に比例しない。",
                        "色を「<strong>管理</strong>」するには — 例えば二枚のパネルが十分近いかを一つの数で判定するには — 距離=差が成り立つより均一な座標が要った。"]),
            dict(h2="7. より均一に — CIE 1976 u'v'とCIELAB", fig="lab",
                 cap="CIELAB色空間。L*は明るさ(0~100)、a*は緑(−)↔赤(+)、b*は青(−)↔黄(+)。第1部の反対色構造をそのまま座標軸にした。色差は今や二点間の距離だ。",
                 paras=["最初の補正は、座標を非線形に引き伸ばしマクアダム楕円を可能な限り<strong>円</strong>に近づけることだった。こうして生まれたのがCIE 1976 UCS、u'v'色度図(下の式)。楕円がずっと均等に広がる。",
                        "同年CIEはさらに進み、明るさまで含む三次元均一色空間<strong>CIELAB(L*a*b*)</strong>を定義した。L*は明るさ(0黒~100白)、a*は緑(−)↔赤(+)、b*は青(−)↔黄(+)の軸で、第1部の<strong>反対色</strong>構造をそのまま座標にしたものだ。",
                        "変換はXYZを基準白で割り、立方根状の関数を通す。効果は単純だ。二色の差を<strong>ただ二点間の距離</strong>として測れるようになった。"],
                 fml=["uv", "lab"]),
            dict(h2="8. 色差の完成 — ΔE76からCIEDE2000", fig="de",
                 cap="色差ΔEの進化。ΔE76は単純なユークリッド距離。CIEDE2000は明度・彩度・色相への重み(SL・SC・SH)と青領域補正(回転項RT)を加え、体感差に合わせる。",
                 paras=["CIELABで二色の差はユークリッド距離、ΔE*ab(下の式、1976)だ。直感的で長く使われたが、CIELABも完全に均一ではなく、特に<strong>青・高彩度</strong>領域で人の感覚とずれた。",
                        "そこで1994年、続いて2000年に補正式が出た。現在の産業標準<strong>CIEDE2000(ΔE00)</strong>は、明度・彩度・色相の差にそれぞれ重み(SL・SC・SH)を与え、彩度が高いほど差を弱く見積もり、青領域の色相-彩度相互作用を捉える<strong>回転項(RT)</strong>まで加える。",
                        "式は長く複雑だが、目的は一つ — 計算したΔE一つの数が人の実際の色差感覚に最大限合うようにすること。ΔE00が約1なら訓練された目がかろうじて区別する差で、それが今日のディスプレイ・印刷・塗料の<strong>品質基準</strong>になる。"],
                 fml=["de76", "de00"]),
        ],
        closing_h2="二編を終えて",
        closing="第1部が「眼が色をつくる」生物学なら、第2部は「その色を皆が共有する数に結んだ」標準の歴史だった。L・M・S三つの錐体に始まりX・Y・Z三刺激値、馬蹄形色度図、そしてCIEDE2000まで — 私たちが毎日見る画面の色を「正確だ」と言えるのは、この一世紀の測定のおかげだ。実際のディスプレイでこの座標が色域・キャリブレーション・カラーマネジメントにどう使われるかは、また次の機会に。",
        fig_word="図",
        prev_label="← 第1部", prev_text="私たちはどう色を見るか",
        author_desc="色彩科学・ディスプレイ光学の技術解説。本稿の科学的内容は公開された学術・標準(CIE)資料に基づき、図はすべて自作。",
        src="CIE標準(CIE 15、測色/色差)および人間視覚・色彩科学の標準的な教科書水準の内容を基に再構成。XYZ等色関数は公開された解析的近似式で計算。図はすべてオリジナル制作。",
        all_list="AI・テック一覧", home="ホーム",
    )
    C["zh"] = dict(
        title="色彩的科学② 把颜色变成数字 — 从CIE 1931到CIEDE2000",
        desc="如何用数字定义颜色：颜色匹配实验、匹配函数为何出现负值、虚拟原色X/Y/Z、CIE 1931马蹄形色度图、麦克亚当椭圆与非均匀性、CIE 1976 u'v'/CIELAB，以及色差ΔE到CIEDE2000 — 色彩科学第2部图解。",
        keywords="CIE 1931, 颜色匹配函数, 色度图, 三刺激值, XYZ, 麦克亚当椭圆, CIELAB, CIE 1976, CIEDE2000, 色差, deltaE, 色域, 显示色彩, lucky please",
        og_title="把颜色变成数字 — 从CIE 1931到CIEDE2000",
        og_desc="颜色匹配函数为何出现负值？人类量化颜色的一个世纪，图解呈现。色彩的科学·第2部。",
        kicker="色彩的科学 · 第2部", h1="把颜色变成数字",
        sub="从CIE 1931到CIEDE2000 — 人类测量颜色并把它钉入坐标的一个世纪",
        lead="第1部我们看到，颜色归根结底是L·M·S三个数的<strong>比例</strong>。但要把「我看到的红」精确传达给别人，需要的不是感觉，而是人人都能复现的<strong>标准坐标</strong>。1931年，国际照明委员会(CIE)让人坐到实验台前测量颜色，其结果成为今天一切显示器、相机与印刷的基石。",
        secs=[
            dict(h2="1. 测量颜色 — 颜色匹配", fig="match",
                 cap="颜色匹配实验。视场分为两半，一半照射待测单色光，另一半照射三原色(R 700·G 546·B 436nm)的混合，转动旋钮直到两半看起来相同。",
                 paras=["方法出奇地简单而优美。把圆形视场分为两半，一半照射待测的<strong>单色光</strong>(单一波长)，另一半照射三种原色，红(700nm)、绿(546.1nm)、蓝(435.8nm)的混合。",
                        "观察者转动三原色的亮度旋钮，使两半看起来<strong>完全相同</strong>。匹配瞬间的三个值R·G·B，就是该波长之色「用三原色表示的坐标」。对所有可见波长重复此实验，便得到三条曲线：每个波长各需多少R·G·B。"]),
            dict(h2="2. 颜色匹配函数 r̄ ḡ b̄", fig="cmf_rgb",
                 cap="CIE RGB颜色匹配函数 — 复现各波长所需的R·G·B量。注意r̄(λ)在约440–545nm之间降到零以下，变为负值。",
                 paras=["这三条曲线就是<strong>颜色匹配函数</strong>。r̄(λ)·ḡ(λ)·b̄(λ)告诉你复现每个波长各需多少R·G·B。任意光的颜色由此积分得到。",
                        "可初看曲线会发现怪处。<strong>r̄(λ)有一段降到零以下，变成了负值。</strong>给光加上「负的量」究竟是什么意思？每个学颜色匹配的人都会在此卡住。"]),
            dict(h2="3. 为何出现负值", fig="negative",
                 cap="负值的真相。饱和的青色(≈500nm)无法靠相加R·G·B得到。于是把红加到「待测色一侧」使其变浊再匹配 — 方程中红被减去(−R)，记为负值。",
                 paras=["关键在此。某种青色(约500nm)单色光太纯太饱和，无论怎样相加红、绿、蓝都达不到那样的青。混合只会越混越<strong>浊</strong>。",
                        "于是实验者反转思路。不在原色一侧，而是把<strong>少许红加到待测的青色一侧</strong>，让它略微变浊，再与剩下的绿+蓝匹配。写成方程：「待测色 + 红 = 绿 + 蓝」，即「待测色 = 绿 + 蓝 − 红」。这被<strong>减去的红</strong>正是负的r̄。",
                        "换言之，负值是「加到另一侧之光」的记录。并非物理上减光，而是人类色觉的极限 — <strong>有些颜色只有靠减才能匹配</strong> — 被刻进了数字。它也意味着仅凭三种真实原色，无法用正值表示一切颜色。"]),
            dict(h2="4. 消除负值的X·Y·Z", fig="xyz_cmf",
                 cap="CIE 1931 XYZ颜色匹配函数。用虚拟原色X·Y·Z改写后，三函数在全域均为正。ȳ(λ)被设计为与人感知的亮度(光度)一致。",
                 paras=["负值不便于计算。于是CIE做了巧妙的变换：定义了三个并不真实存在的<strong>虚拟原色</strong>X·Y·Z。它们比任何真实光都更饱和、物理上无法制造，但作为坐标却完美运作。",
                        "用这些原色改写后，所有匹配函数x̄·ȳ·z̄在<strong>全域均为正</strong>。更妙的是，ȳ(λ)被设计为与人感知的亮度一致，故单一Y值即为光度。",
                        "对任意光S(λ)，如下积分即得三个数X·Y·Z，即<strong>三刺激值</strong>。第1部的「L·M·S三个数」在此被标准化为X·Y·Z三个数。"],
                 fml=["xyz_int"]),
            dict(h2="5. CIE 1931色度图 — 马蹄形", fig="chromaticity",
                 cap="CIE 1931 xy色度图。外缘曲线为纯单色光(光谱轨迹)，下方直线为紫线，中心为白点。一切真实颜色都落在此马蹄形内。显示器色域是其中的三角形。",
                 paras=["三刺激值X·Y·Z是三维的，不便画在纸上。于是剥离亮度，只把「色相·饱和度」投影到二维(下式)。这个(x, y)平面便是著名的<strong>马蹄形</strong>色度图。",
                        "外缘曲线是纯单色光的<strong>光谱轨迹</strong>，下方直线是连接红与蓝的紫线，中心是白点。一切真实颜色都落在此马蹄形内。显示器能表现的颜色范围(<strong>色域, gamut</strong>)画作其中的三角形 — sRGB、DCI-P3、BT.2020是逐渐变大的三角形。"],
                 fml=["xy"]),
            dict(h2="6. 1931的局限 — 并不均匀", fig="macadam",
                 cap="麦克亚当椭圆(概念图)。「刚能察觉的色差」边界，随位置不同大小与方向各异 — 绿色区巨大(迟钝)，蓝色区很小(敏感)。距离 ≠ 体感差异。",
                 paras=["CIE 1931是一场革命，却有一个弱点：在色度图上，<strong>相同的距离并不意味着相同的「色差」</strong>。",
                        "1942年麦克亚当测量了人「刚能察觉差异」的边界，结果呈现为小椭圆。问题是这些椭圆的大小与方向随位置各不相同 — 绿色区巨大(迟钝)，蓝色区很小(敏感)。即便在坐标上测两色的距离，也与人的体感差异不成比例。",
                        "要<strong>管理</strong>颜色 — 比如用一个数判定两块面板是否足够接近 — 就需要距离=差异成立的更均匀坐标。"]),
            dict(h2="7. 更均匀 — CIE 1976 u'v'与CIELAB", fig="lab",
                 cap="CIELAB色空间。L*为亮度(0~100)，a*为绿(−)↔红(+)，b*为蓝(−)↔黄(+)。把第1部的对立色结构直接化为坐标轴。色差如今就是两点间的距离。",
                 paras=["第一次修正是将坐标非线性地重新拉伸，使麦克亚当椭圆尽量接近<strong>圆</strong>。由此产生了CIE 1976 UCS，即u'v'色度图(下式)，椭圆铺展得均匀得多。",
                        "同年CIE更进一步，定义了包含亮度的三维均匀色空间<strong>CIELAB(L*a*b*)</strong>。L*为亮度(0黑~100白)，a*为绿(−)↔红(+)，b*为蓝(−)↔黄(+)轴 — 正是把第1部的<strong>对立色</strong>结构直接化为坐标。",
                        "变换是把XYZ除以参考白，再经一个立方根状函数。关键效果很简单：两色之差如今可<strong>仅以两点间的距离</strong>来度量。"],
                 fml=["uv", "lab"]),
            dict(h2="8. 色差的完成 — 从ΔE76到CIEDE2000", fig="de",
                 cap="色差ΔE的演进。ΔE76是简单的欧氏距离；CIEDE2000为明度·彩度·色相加权(SL·SC·SH)并加入蓝区修正(旋转项RT)，以贴合体感。",
                 paras=["在CIELAB中，两色之差是欧氏距离ΔE*ab(下式，1976)。直观且沿用已久，但CIELAB也并非完全均匀，尤其在<strong>蓝色与高彩度</strong>区域与人的感觉偏离。",
                        "于是1994年、继而2000年出现了修正式。当前的工业标准<strong>CIEDE2000(ΔE00)</strong>对明度、彩度、色相之差分别加权(SL·SC·SH)，彩度越高越弱化差异，并加入捕捉蓝区色相-彩度相互作用的<strong>旋转项(RT)</strong>。",
                        "公式冗长复杂，但目的只有一个 — 让计算出的单个ΔE尽量贴合人实际感受的色差。ΔE00约为1，便是训练有素的眼睛勉强能分辨的差异，那正是今天显示器、印刷与涂料的<strong>质量标准</strong>。"],
                 fml=["de76", "de00"]),
        ],
        closing_h2="两部作结",
        closing="若第1部是「眼睛造出颜色」的生物学，第2部便是「把那颜色钉成人人共享之数」的标准史。从L·M·S三种视锥，到X·Y·Z三刺激值、马蹄形色度图，再到CIEDE2000 — 我们之所以能说每天所见屏幕的颜色「准确」，全靠这一个世纪的测量。这些坐标在真实显示器中如何用于色域、校准与色彩管理，留待下次再谈。",
        fig_word="图",
        prev_label="← 第1部", prev_text="我们如何看见颜色",
        author_desc="色彩科学与显示光学的技术解说。本文科学内容基于公开的学术与标准(CIE)资料，图表均为原创制作。",
        src="基于CIE标准(CIE 15，色度学/色差)及人类视觉与色彩科学的标准教科书级内容重构。XYZ颜色匹配函数由公开的解析近似式计算。图表均为原创。",
        all_list="全部 AI·科技文章", home="首页",
    )
    return C[lang]
