"""Translate spacex-vs-tesla KR to EN."""
import shutil
src = 'public/blog/spacex-vs-tesla/index.html'
dst = 'public/blog/spacex-vs-tesla-en/index.html'
shutil.copy(src, dst)
with open(dst, 'r', encoding='utf-8') as f:
    h = f.read()

swaps = [
    ('<html lang="ko">', '<html lang="en">'),
    ('SpaceX vs Tesla — 머스크 두 제국 정밀 비교 (시총·수익·기술 moat·미래) | Lucky Please',
     "SpaceX vs Tesla — Musk's Two Empires Side-by-Side (Cap, Profit, Moat, Future) | Lucky Please"),
    ('$1.75T SpaceX vs $1.2T Tesla — 머스크의 두 제국을 시총, 수익성, 기술 moat, 성장 전망, 리스크 5축으로 비교. IPO 시점 어느 쪽이 더 매력적? Bull/Bear 시나리오까지.',
     "$1.75T SpaceX vs $1.2T Tesla — Musk's two empires compared on 5 axes: cap, profitability, tech moat, growth, risk. Which is more attractive at IPO time? Bull/Bear scenarios included."),
    ('SpaceX vs Tesla, 머스크 두 회사 비교, SpaceX IPO Tesla, 시총 비교, 자동차 vs 우주, lucky please',
     'SpaceX vs Tesla, Musk companies compared, SpaceX IPO Tesla, market cap comparison, automotive vs space, lucky please'),
    ('spacex-vs-tesla/', 'spacex-vs-tesla-en/'),
    ('hreflang="ko" href="https://luckyplz.com/blog/spacex-vs-tesla-en/"',
     'hreflang="ko" href="https://luckyplz.com/blog/spacex-vs-tesla/"'),
    ('"inLanguage":"ko"', '"inLanguage":"en"'),
    ('SpaceX vs Tesla — 머스크 두 제국 정밀 비교',
     "SpaceX vs Tesla — Musk's Two Empires Side-by-Side"),
    ('$1.75T vs $1.2T. 시총·수익·기술·미래·리스크 5축 비교.',
     '$1.75T vs $1.2T. 5-axis comparison: cap, profit, moat, future, risk.'),
    ('SpaceX vs Tesla — 머스크 두 제국',
     "SpaceX vs Tesla — Musk's Two Empires"),
    ('시총·수익·기술 moat·리스크 5축 비교 분석.',
     '5-axis comparison: cap, profit, moat, risk.'),
    # Hero
    ('머스크의 두 제국</h1>', "Musk's Two Empires</h1>"),
    ('$1.75T 우주 + $1.2T 자동차. 동일한 머스크가 이끄는 두 회사를 시총·수익성·기술 moat·미래 잠재력·리스크 <strong>5축으로 정밀 비교</strong>. IPO 시점에 어느 쪽이 더 매력적인 베팅인가?',
     "$1.75T space + $1.2T cars. Same Musk runs both — comparing them on <strong>5 axes</strong> (cap, profit, moat, growth, risk). At IPO time, which is the more attractive bet?"),
    ('난이도 ★★☆☆☆', 'Difficulty ★★☆☆☆'),
    ('읽는 시간 8분', 'Read 8 min'),
    ('2026.05.05 기준', 'As of 2026.05.05'),
    ('사상 최대 IPO · 비상장 (현재) · 21 IB 주관 · xAI 합병 후',
     'Largest IPO ever · Currently private · 21 underwriters · Post xAI merger'),
    ('상장 16년 · S&amp;P 500 편입 · Robotaxi · FSD v13',
     '16 years public · S&amp;P 500 · Robotaxi · FSD v13'),
    # TOC
    ('한눈에 보는 비교 (요약 점수표)', 'Quick Comparison (Score Sheet)'),
    ('축 1: 시가총액 + 매출 배수', 'Axis 1: Market Cap + Sales Multiple'),
    ('축 2: 수익성 + 현금흐름', 'Axis 2: Profitability + Cash Flow'),
    ('축 3: 기술 moat + 진입장벽', 'Axis 3: Tech Moat + Entry Barrier'),
    ('축 4: 미래 잠재력 (5년·10년)', 'Axis 4: Future Potential (5Y·10Y)'),
    ('축 5: 리스크 매트릭스', 'Axis 5: Risk Matrix'),
    ('합산 판정 + 포트폴리오 배분', 'Verdict + Portfolio Allocation'),
    ('최종 결론: 둘 다 vs 한쪽', 'Final: Both vs One'),
    # Section headers
    ('한눈에 보는 비교', 'Quick Comparison'),
    ('5개 축에서 SpaceX 가 3승, Tesla 가 1승, 무승부 1. 단 평가 기준에 따라 결과 달라짐.',
     'Across 5 axes: SpaceX 3W, Tesla 1W, 1 draw. But the criteria-weighting changes the outcome.'),
    ('시총', 'Cap'),
    ('수익성', 'Profit'),
    ('기술 moat', 'Tech moat'),
    ('미래 잠재력', 'Future'),
    ('리스크', 'Risk'),
    ('EBITDA 마진 60%+', 'EBITDA margin 60%+'),
    ('5년 경쟁자 부재 vs FSD 추격당함', 'No competitor 5y vs FSD chased'),
    ('화성 + 궤도 DC + xAI', 'Mars + orbital DC + xAI'),
    ('둘 다 머스크 거버넌스', 'Both face Musk governance'),
    ('무승부', 'Draw'),
    # Axis 1
    ('축 1: 시총 + 매출 배수', 'Axis 1: Market Cap + Sales Multiple'),
    ('시총 차이는 +46%, 그런데 매출 배수는 SpaceX 가 3.5배 비싸다.',
     'Cap differs +46%, yet SpaceX sales multiple is 3.5x more expensive.'),
    ('지표', 'Metric'),
    ('시총', 'Market Cap'),
    ('2025 매출', '2025 Revenue'),
    ('P/S 매출 배수', 'P/S Multiple'),
    ('2026E 매출', '2026E Revenue'),
    ('2026E P/S', '2026E P/S'),
    ('주요 비교 군', 'Comparable'),
    ('자동차 평균 (1.5×)', 'Auto industry avg (1.5×)'),
    ('해석', 'Interpretation'),
    ('SpaceX 가 시총은 +46% 더 높지만,', "SpaceX cap is +46% higher,"),
    ('매출은 1/6 수준', 'but revenue is only ~1/6 the size'),
    ('. 즉 매출 배수에서 5배 비싸게 거래된다는 뜻. NVDA 가 30배인 점과 비교하면, SpaceX 는 NVDA 의 2배 프리미엄.',
     '. So sales multiple is 5x more expensive. Compared to NVDA at 30x, SpaceX is at 2x NVDA premium.'),
    ('Tesla 는 자동차 산업 평균 (1.5배) 대비 8배 프리미엄.', "Tesla trades at 8x the auto-industry average (1.5x)."),
    ('이미 robotaxi/FSD 옵션이 가격에 반영', 'meaning robotaxi/FSD optionality is priced in'),
    ('됐다는 뜻. 추가 상승 여지는 robotaxi 매출 본격화 시점에 한정.',
     '. Further upside is gated on robotaxi revenue actually materializing.'),
    # Axis 2
    ('축 2: 수익성 + 현금흐름', 'Axis 2: Profitability + Cash Flow'),
    ('Tesla 가 흑자 성숙기, SpaceX 는 xAI 합병 후 적자.',
     'Tesla is in mature profitability, SpaceX is loss-making post xAI merger.'),
    ('2025 매출 이익', '2025 Net Income'),
    ('2024 vs 2025', '2024 vs 2025'),
    ('운영 현금흐름', 'Operating Cash Flow'),
    ('자유 현금흐름 (FCF)', 'Free Cash Flow'),
    ('2025 Capex', '2025 Capex'),
    ('EBITDA 마진 (Starlink/Auto)', 'EBITDA margin (Starlink/Auto)'),
    ('월 burn rate', 'Monthly burn'),
    ('+$791M → -$5B', '+$791M → -$5B'),
    ('$8B → $10B 안정 성장', '$8B → $10B steady'),
    ('(매출초과)', '(exceeds revenue)'),
    ('~$1B (xAI)', '~$1B (xAI)'),
    ('+$1.3B 흑자', '+$1.3B profit'),
    ('왜 이렇게 다른가', 'Why So Different'),
    ('Tesla 는', 'Tesla has reached'),
    ('16년 상장 → 20년 영업 → 흑자 안정기', '16 years public, 20 years operating — mature profitability'),
    ('도달. 분기마다 $2-3B 순이익. 자동차 사업 단독으로 이미 cash machine 이 됐고, robotaxi/FSD 가 추가 upside.',
     '. Quarterly net income $2-3B. Auto business alone is a cash machine; robotaxi/FSD is upside.'),
    ('SpaceX 는', 'SpaceX has'),
    ('Starlink 단독은 매우 수익적', 'Starlink alone highly profitable'),
    ('(EBITDA 마진 60-63%). 그러나 xAI 합병으로 $6.4B 영업손실 흡수 + Starship 개발에 $15B+ 쏟아부음.',
     ' (EBITDA margin 60-63%). But xAI merger absorbed $6.4B operating loss + $15B+ Starship dev.'),
    ('합산 손익은 큰 폭 적자', 'Consolidated P&L is deeply negative'),
    ('. 이 적자를 Starlink 흑자로 흡수하는 구조가 4-5년 지속될 가능성.',
     '. Likely 4-5 years where Starlink profits absorb the rest.'),
    ('실질 의미:', 'Practical meaning:'),
    ('Tesla 사면 즉시 배당 가능 자산 (현재는 안 함)', "Tesla = dividend-capable asset today (though doesn't pay yet)"),
    ('SpaceX 사면 4-5년은 적자 + 변동성', 'SpaceX = 4-5 years of losses + volatility'),
    # Axis 3
    ('축 3: 기술 moat + 진입장벽', 'Axis 3: Tech Moat + Entry Barrier'),
    ('SpaceX 의 moat 가 더 깊고 더 넓다.', "SpaceX's moat is deeper and wider."),
    ('SpaceX moat — 5년 경쟁자 부재', 'SpaceX moat — no competitor for 5 years'),
    ('발사:', 'Launch:'),
    ('82% 글로벌 상업 발사 점유. Blue Origin New Glenn 은 진입했지만 재사용 규모 미입증. ULA Vulcan 은 정부 second-source 역할만.',
     '82% global commercial launch. Blue Origin New Glenn entered but reuse-at-scale unproven. ULA Vulcan = government second-source.'),
    ('5년 안에 진정한 경쟁자 등장 어려움.', 'No real competitor within 5 years.'),
    ('Starlink:', 'Starlink:'),
    ('65% 활성위성 점유. Amazon Kuiper 가 추격 시작했지만 위성 1,000개 vs SpaceX 의 12,000개. AST SpaceMobile 은 D2C 만 노림.',
     '65% active satellites. Kuiper started catching up but ~1,000 sats vs SpaceX 12,000. AST SpaceMobile = D2C only.'),
    ('5년 격차 더 벌어질 가능성.', 'Gap likely widens over 5 years.'),
    ('제조 속도:', 'Manufacturing tempo:'),
    ('부스터·스테이지 한 세트 15초 단위 양산. 경쟁사 모방 불가능 수준의 manufacturing tempo.',
     'Booster + stage every ~15 seconds at peak. Manufacturing tempo nobody can replicate.'),
    ('정부:', 'Government:'),
    ('Space Force PLEO 97% SpaceX 배정. 안보 인프라로 lock-in.',
     'Space Force PLEO 97% to SpaceX. National security infrastructure lock-in.'),
    ('Tesla moat — 추격당하고 있음', 'Tesla moat — being chased down'),
    ('EV:', 'EV:'),
    ('시장 점유율 정점에서 하락. 미국 ~50%→32%, 중국 ~20%→8% (BYD 가 1위). EU에서도 Volkswagen ID.4 / BMW i4 추격.',
     'Market share peaking. US ~50%→32%, China ~20%→8% (BYD #1). VW ID.4 / BMW i4 chasing in EU.'),
    ('EV moat 약화 진행 중.', 'EV moat is eroding.'),
    ('Supercharger:', 'Supercharger:'),
    ('NACS 표준 확장으로 다른 OEM 까지 사용. 매출 증가하지만 차별화 약해짐.',
     'NACS standard expanded to other OEMs. Revenue grows but differentiation fades.'),
    ('FSD:', 'FSD:'),
    ('Waymo 가 robotaxi 상업 운영에서 앞서감. Tesla FSD v13 은 supervised 만 인증.',
     'Waymo leads robotaxi commercial operations. Tesla FSD v13 only certified supervised.'),
    ('Robotaxi 경쟁이 이미 시작됨.', 'Robotaxi race has already started.'),
    ('Energy storage:', 'Energy storage:'),
    ('Megapack 매출은 빠르게 늘지만 LG·삼성·CATL 가 따라잡음.',
     'Megapack revenue scaling fast but LG/Samsung/CATL catching up.'),
    ('구조적 차이', 'Structural Difference'),
    ('SpaceX 의 moat 는', "SpaceX's moat is"),
    ('물리·자본·시간', 'physics + capital + time'),
    ('이 핵심. 새 발사장 건설, 위성 12,000개 발사, FAA 승인까지 5-10년 소요. 누구도 따라잡을 수 없는 구조적 진입 장벽.',
     '. New launch sites, 12,000 satellites, FAA approvals = 5-10 years. Structural barriers nobody can leap.'),
    ('Tesla 의 moat 는', "Tesla's moat is"),
    ('소프트웨어·브랜드', 'software + brand'),
    ('가 핵심. FSD 데이터·차량 OTA 업데이트는 진입 장벽이지만, Waymo·BYD·Mobileye 가 충분히 따라올 수 있는 영역.',
     '. FSD data + OTA are barriers but Waymo, BYD, Mobileye can catch up.'),
    # Axis 4
    ('축 4: 미래 잠재력 (5년·10년)', 'Axis 4: Future Potential (5Y·10Y)'),
    ('SpaceX 가 압도적. 단, 실현 확률은 별개.',
     'SpaceX is overwhelming. But execution probability is separate.'),
    ('잠재력', 'Potential'),
    ('2030 매출 추정', '2030 Revenue Est.'),
    ('2030 시총 추정', '2030 Cap Est.'),
    ('핵심 베팅', 'Key bets'),
    ('화성·궤도 DC·D2C', 'Mars · orbital DC · D2C'),
    ('Robotaxi·FSD·Optimus', 'Robotaxi · FSD · Optimus'),
    ('최대 upside (Bull)', 'Max upside (Bull)'),
    ('$10T (화성 식민)', '$10T (Mars colony)'),
    ('$5T (FSD 글로벌)', '$5T (FSD global)'),
    ('최대 downside (Bear)', 'Max downside (Bear)'),
    ('$0.5T (Starship 영구실패)', '$0.5T (Starship perma-fail)'),
    ('$0.7T (EV 정점)', '$0.7T (EV peak)'),
    ('실현 확률 (5년)', 'Probability (5Y)'),
    ('SpaceX의 베팅', "SpaceX's bets"),
    ('① 화성 식민 (10년+):', '① Mars colony (10y+):'),
    ('2030 무인 5기, 2032 유인 첫 시도. 성공 시 시총 $10T+ 이론 가능. 실패 확률 50%+. 머스크 자기평가 50% 적시 도달 확률.',
     '5 uncrewed by 2030, first crewed by 2032. Success → $10T+ cap theoretical. 50%+ failure prob. Musk self-rates 50% on-time.'),
    ('② 궤도 데이터센터 (5년):', '② Orbital data centers (5y):'),
    ('1M 위성 컨스털레이션 → AI 컴퓨트 100GW/년. 지상 DC 전력 병목 우회. ARK 추정 25% 비용 절감. 시총 추가 $2-3T 가치.',
     '1M satellite constellation → 100GW/yr AI compute. Sidesteps ground-DC power bottleneck. ARK: -25% vs terrestrial. Adds $2-3T to cap.'),
    ('③ Direct-to-Cell (3년):', '③ Direct-to-Cell (3y):'),
    ('4G→150Mbps 차세대. EchoStar 스펙트럼 기반. 2028 mass market 진입. 통신 산업 재편 가능.',
     '4G → 150Mbps next-gen. EchoStar spectrum based. Mass market entry 2028. Could reshape telecom industry.'),
    ('Tesla의 베팅', "Tesla's bets"),
    ('① Robotaxi (3-5년):', '① Robotaxi (3-5y):'),
    ('2026 Cybercab 양산 시작. 2027 정식 서비스. 시장 규모 $1T+ 추정 (2030). 단 Waymo 가 이미 8개 도시 운영 중 — 경쟁 매우 심함.',
     '2026 Cybercab production starts. 2027 commercial service. $1T+ market est. (2030). Waymo already in 8 cities — heavy competition.'),
    ('② Optimus (5년+):', '② Optimus (5y+):'),
    ('2026 시범 양산, 2030 mass market 가능. 인간형 로봇 시장 추정 $2T+ (2035). 현재 가장 대담한 베팅.',
     '2026 pilot production, 2030 mass market. Humanoid robot market est. $2T+ (2035). Boldest bet currently.'),
    ('③ FSD 글로벌 라이센싱 (3년):', '③ FSD global licensing (3y):'),
    ('다른 자동차 회사에 FSD 라이센스. 추정 매출 $20B+/년 가능. 단 OEM 들이 자체 솔루션 선호하는 추세.',
     'License FSD to other OEMs. Est. $20B+/yr revenue. But OEMs prefer in-house solutions.'),
    # Axis 5
    ('축 5: 리스크 매트릭스', 'Axis 5: Risk Matrix'),
    ('둘 다 머스크 거버넌스 리스크에서 공통, 종류는 다르다.',
     'Both share Musk governance risk, but the types differ.'),
    ('머스크 헤드라인 (트윗)', 'Musk headlines (tweets)'),
    ('中高 (변동성 2x)', 'Mid-high (vol 2x)'),
    ('高 (한 트윗 -10%)', 'High (one tweet -10%)'),
    ('경쟁자 진입', 'Competitor entry'),
    ('낮음 (5년 부재)', 'Low (none for 5y)'),
    ('高 (BYD·Waymo)', 'High (BYD, Waymo)'),
    ('실행 리스크 (지연)', 'Execution risk (delays)'),
    ('高 (Starship 5x 미달)', 'High (Starship 5x behind)'),
    ('中 (Cybercab/Optimus)', 'Mid (Cybercab/Optimus)'),
    ('규제 리스크', 'Regulatory'),
    ('中 (FCC·반독점)', 'Mid (FCC, antitrust)'),
    ('中 (FSD 인증·NHTSA)', 'Mid (FSD cert, NHTSA)'),
    ('거시 (금리·경기)', 'Macro (rates, economy)'),
    ('낮음 (정부계약 비중)', 'Low (govt-contract weight)'),
    ('高 (EV 소비재)', 'High (EV consumer good)'),
    ('자본 요구', 'Capital intensity'),
    ('매우 높음 ($20B/년)', 'Very high ($20B/yr)'),
    ('중 (FCF 흑자)', 'Mid (FCF positive)'),
    ('중국 노출', 'China exposure'),
    ('없음', 'None'),
    ('25% 매출', '25% of revenue'),
    ('SpaceX 의 가장 큰 리스크', "SpaceX's biggest risk"),
    ('Starship V3 의 binary outcome.', 'Starship V3 binary outcome.'),
    ('V3 가 정상화되면 ($100/kg 진입) 모든 미래 베팅 (궤도 DC, 화성, D2C) 이 가능. 실패하면 가치의 2/3가 무너짐.',
     'If V3 normalizes ($100/kg) → all future bets work (orbital DC, Mars, D2C). If it fails → 2/3 of value collapses.'),
    ('자본 요구 폭주.', 'Capital intensity explosion.'),
    ('2025 Capex $20.7B 가 매출 $15.5B 를 초과했고, 이 추세가 5-7년 지속 예상.',
     '2025 Capex $20.7B exceeds revenue $15.5B; trend likely lasts 5-7 years.'),
    ('Tesla 의 가장 큰 리스크', "Tesla's biggest risk"),
    ('EV 시장 정점 + 중국 추격.', 'EV market peak + Chinese chase.'),
    ('미국 EV 점유율 32%로 하락. 중국에서 BYD 에 추월당함. 매출 2030 까지 $200B 도달 시나리오는 robotaxi/Optimus 가 살아나야 함.',
     'US EV share fell to 32%. Surpassed by BYD in China. The path to $200B by 2030 requires robotaxi/Optimus to materialize.'),
    ('경기 민감도.', 'Macro sensitivity.'),
    ('EV 는 고가 소비재. 금리 인상기 / 경기 침체 시 첫 번째로 타격.',
     'EVs are high-ticket consumer goods. First hit during rate hikes / recession.'),
    # Section 6
    ('합산 판정 + 포트폴리오 배분', 'Verdict + Portfolio Allocation'),
    ('머스크 베팅의 핵심: 두 회사 비중 어떻게 나눠야 하나.', 'The core question: how to split between the two.'),
    ('리스크 허용도별 배분', 'Allocation by risk tolerance'),
    ('보수형 (5-10년 보유 가능):', 'Conservative (5-10y holdable):'),
    ('SpaceX 30% + Tesla 40% + 우주·AI 우회 ETF 30%. SpaceX 변동성을 ETF로 흡수.',
     'SpaceX 30% + Tesla 40% + space/AI ETF 30%. ETF absorbs SpaceX volatility.'),
    ('중립형:', 'Neutral:'),
    ('SpaceX 50% + Tesla 30% + Robotaxi/궤도DC adjacent 20%. SpaceX 가 더 큰 upside, Tesla 가 안정 cash flow.',
     'SpaceX 50% + Tesla 30% + robotaxi/orbital-DC adjacent 20%. SpaceX = bigger upside, Tesla = stable cash flow.'),
    ('적극형:', 'Aggressive:'),
    ('SpaceX 70% + Tesla 30%. SpaceX Bull case 기대 + Tesla 를 변동성 hedge 로.',
     'SpaceX 70% + Tesla 30%. SpaceX Bull case + Tesla as volatility hedge.'),
    ('방어형 (둘 다 변동성 회피):', 'Defensive (avoiding both):'),
    ('각각 5% 이하 + 현금 / 인덱스 ETF 위주. 머스크 헤드라인 리스크 회피.',
     'Each ≤5% + cash/index ETF heavy. Avoiding Musk headline risk entirely.'),
    ('이미 Tesla 보유자 — SpaceX 진입 여부', 'Already hold Tesla — should you enter SpaceX'),
    ('Tesla 보유 시 머스크·우주 혁신 노출을 이미 가지고 있음 (Tesla 가 SpaceX 지분 $2B 보유). 그러나 정량적 비중은 작음. SpaceX IPO 진입 시 추가 순노출 +50% 가능.',
     'Holding Tesla already gives Musk/space innovation exposure (Tesla owns $2B SpaceX equity). But weighted small. SpaceX IPO adds +50% net exposure.'),
    ('권장:', 'Recommendation:'),
    ('기존 Tesla 비중의 20-30% 를 SpaceX 로 이전. 또는 우회 ETF 로 점진 분산.',
     'Migrate 20-30% of Tesla allocation to SpaceX. Or diversify gradually via proxy ETFs.'),
    ('이미 SpaceX 우회 ETF 보유자 — Tesla 추가 여부', 'Already hold SpaceX proxy ETF — add Tesla?'),
    ('XOVR/DXYZ 등 SpaceX 노출만 있다면 Tesla 추가는 의미 있음.', 'If only have SpaceX exposure via XOVR/DXYZ, adding Tesla makes sense.'),
    ('Tesla 의 흑자 cash flow 가 SpaceX 적자기 4-5년 동안 portfolio 안정화', "Tesla's positive cash flow stabilizes portfolio during SpaceX's 4-5 year loss period"),
    ('그러나 둘 다 머스크 헤드라인 리스크에 노출. 분산은 머스크 외 다른 자산 (NVDA, MSFT, MS, BRK 등) 으로 해야 의미 있음.',
     'But both face Musk headline risk. True diversification needs non-Musk assets (NVDA, MSFT, MS, BRK, etc.).'),
    # Section 7
    ('최종 결론: 둘 다 vs 한쪽', 'Final: Both vs One'),
    ('최종 정리', 'Final summary'),
    ('SpaceX 가 더 매력적인 경우:', 'SpaceX is more attractive when:'),
    ('5-10년 보유 가능 + 변동성 ±30% 견딤<br>· 화성·궤도 DC·xAI 의 미래 가치 믿음<br>· 자본 요구 폭주 4-5년 견딜 portfolio 여유',
     '5-10y holdable + can stomach ±30% volatility<br>· Believe in Mars / orbital DC / xAI future value<br>· Portfolio can absorb 4-5y capital intensity'),
    ('Tesla 가 더 매력적인 경우:', 'Tesla is more attractive when:'),
    ('2-3년 단기 보유 + 변동성 ±20% 견딤<br>· Robotaxi·FSD 의 가까운 매출 실현 믿음<br>· EV 시장 정점이지만 인간형 로봇 후속 신뢰',
     '2-3y shorter hold + ±20% volatility OK<br>· Believe in near-term robotaxi/FSD revenue<br>· Trust humanoid robotics succession of EV'),
    ('둘 다 보유:', 'Both:'),
    ('머스크 자체 ecosystem 베팅<br>· 5년 portfolio 의 Bull case Sharpe ratio 가장 높음<br>· 단 머스크 헤드라인 한 줄로 둘 다 영향 → 분산은 외부 자산으로',
     'Bet on Musk ecosystem itself<br>· 5y portfolio Sharpe ratio highest under Bull<br>· But one Musk headline hits both → diversify with non-Musk'),
    ('둘 다 회피:', 'Avoid both:'),
    ('머스크 거버넌스 리스크 매우 부담<br>· 미국 메가캡 노출 → S&amp;P 500 인덱스 ETF 가 더 효율적<br>· 화성·robotaxi 회의적 + 경기 침체 우려',
     'Musk governance risk too heavy<br>· US mega-cap exposure → S&amp;P 500 index ETF more efficient<br>· Skeptical on Mars / robotaxi + recession concerns'),
    # HUB
    ('🚀 SpaceX IPO 허브', '🚀 SpaceX IPO Hub'),
    ('관련 콘텐츠', 'Related content'),
    ('$1.75T 심층분석', '$1.75T Deep Dive'),
    ('사는 법', 'How to Buy'),
    ('머스크 자산', "Musk's Net Worth"),
    ('투자 시뮬레이터', 'Invest Simulator'),
    ('href="/blog/spacex-ipo-2026/"', 'href="/blog/spacex-ipo-2026-en/"'),
    ('href="/blog/how-to-buy-spacex-stock/"', 'href="/blog/how-to-buy-spacex-stock-en/"'),
    ('href="/blog/musk-net-worth-after-spacex-ipo/"', 'href="/blog/musk-net-worth-after-spacex-ipo-en/"'),
    ('href="/tools/spacex-invest-sim/"', 'href="/tools/spacex-invest-sim-en/"'),
    ('href="/blog/?cat=industry"', 'href="/blog/?cat=industry&amp;lang=en"'),
    # Footer
    ('본 분석은 ARK Invest, Sacra Equity Research, PitchBook, Reuters, Bloomberg, CNBC, Quilty Space 자료 기반 추정. 모든 수치 (시총·매출·시장점유율) 는 2026.05 기준이며 실제와 차이 가능. SpaceX 의 공식 S-1 공개 시 추정과 다를 수 있음. Tesla 의 robotaxi/Optimus 일정도 머스크 발언 기반 추정. 양사 모두 머스크 거버넌스 리스크 매우 큼.',
     'Analysis based on ARK Invest, Sacra Equity Research, PitchBook, Reuters, Bloomberg, CNBC, Quilty Space. All figures (cap, revenue, market share) are 2026.05 estimates; actuals may differ. SpaceX values will be confirmed at S-1. Tesla robotaxi/Optimus timing is Musk-stated and uncertain. Both face severe Musk governance risk.'),
    ('Last updated · 2026.05.05 · v1.0 · <a href="/blog/?cat=industry">← 산업 더보기</a>',
     'Last updated · 2026.05.05 · v1.0 · <a href="/blog/?cat=industry&amp;lang=en">← More Industry</a>'),
]
for old, new in swaps:
    if old in h:
        h = h.replace(old, new)
with open(dst, 'w', encoding='utf-8') as f:
    f.write(h)
print('Done')
