"""Translate Korean musk-net-worth post to English in-place."""
import shutil

src = 'public/blog/musk-net-worth-after-spacex-ipo/index.html'
dst = 'public/blog/musk-net-worth-after-spacex-ipo-en/index.html'
shutil.copy(src, dst)

with open(dst, 'r', encoding='utf-8') as f:
    h = f.read()

swaps = [
    ('<html lang="ko">', '<html lang="en">'),
    ('SpaceX 상장 후 머스크 자산 — 인류 첫 트릴리오네어? | Lucky Please',
     "Musk's Net Worth After SpaceX IPO — First Trillionaire? | Lucky Please"),
    ('SpaceX IPO ($1.75T) 가 성공하면 머스크 자산 얼마? 6개 회사 (SpaceX 42%, Tesla 13%, X 80%, xAI 합병, Boring, Neuralink) 지분 합산 + 3 시나리오. Forbes·Bloomberg 추정의 정확성도.',
     "How much will Elon Musk be worth after SpaceX IPO ($1.75T)? Stakes across 6 companies (SpaceX 42%, Tesla 13%, X 80%, xAI absorbed, Boring, Neuralink) + 3 scenarios. Forbes vs Bloomberg comparison."),
    ('머스크 자산, Elon Musk net worth, SpaceX 상장 머스크, 트릴리오네어, Forbes 부자 순위, 머스크 지분, lucky please',
     'Elon Musk net worth, Musk wealth, SpaceX IPO Musk, trillionaire, Forbes richest, Musk stake, lucky please'),
    ('musk-net-worth-after-spacex-ipo/', 'musk-net-worth-after-spacex-ipo-en/'),
    ('hreflang="ko" href="https://luckyplz.com/blog/musk-net-worth-after-spacex-ipo-en/"',
     'hreflang="ko" href="https://luckyplz.com/blog/musk-net-worth-after-spacex-ipo/"'),
    ('"inLanguage":"ko"', '"inLanguage":"en"'),
    ('인류 첫 트릴리오네어?', 'First Trillionaire Ever?'),
    ('6개 회사 지분 합산 + Bull/Base/Bear 3 시나리오. SpaceX IPO 가 만들 인류 최초 1조 달러.',
     "Stakes across 6 companies + Bull/Base/Bear scenarios. The first trillionaire SpaceX IPO will make."),
    ('SpaceX 상장 후 머스크 자산<br><strong>인류 첫 트릴리오네어?</strong>',
     "Musk's Net Worth After SpaceX IPO<br><strong>First Trillionaire Ever?</strong>"),
    ('SpaceX IPO ($1.75T)가 성공하면 머스크의 자산은 얼마? 6개 회사 (SpaceX 42% · Tesla 13% · X 80%+ · xAI 합병 · Boring · Neuralink) 지분을 모두 합산해 Bull/Base/Bear 3 시나리오로 계산.',
     "If SpaceX IPO succeeds at $1.75T, how much will Musk be worth? Stakes across 6 companies (SpaceX 42% · Tesla 13% · X 80%+ · xAI absorbed · Boring · Neuralink) under Bull/Base/Bear scenarios."),
    ('난이도 ★☆☆☆☆', 'Easy ★☆☆☆☆'),
    ('읽는 시간 7분', 'Read 7 min'),
    ('2026.05.05 기준', 'As of 2026.05.05'),
    ('Base 시나리오 · IPO 직후', 'Base Scenario · Post-IPO'),
    ('SpaceX 42% + Tesla 13% + X 80% + 기타 합산 (2026.06 추정)',
     'SpaceX 42% + Tesla 13% + X 80% + others (June 2026 est.)'),
    ('목차', 'Contents'),
    ('2026.05 기준 추정 — Forbes·Bloomberg vs 우리', 'May 2026 estimate — Forbes/Bloomberg vs ours'),
    ('6개 회사 지분 분해', 'Six-Company Stake Breakdown'),
    ('3 시나리오: Bull / Base / Bear', '3 Scenarios: Bull / Base / Bear'),
    ('"트릴리오네어" 가능성 — 언제·얼마', '"Trillionaire" Probability — When and How'),
    ('역사적 1위 비교 — Bezos·Arnault·Gates', 'Historical #1s — Bezos / Arnault / Gates'),
    ('주의: 자산 ≠ 현금. 세금·유동성 함정', 'Caveat: Net Worth ≠ Cash'),
    ('2026.05 기준 추정', 'Estimate as of May 2026'),
    ('Forbes / Bloomberg 가 매일 업데이트하는 머스크 자산은 출처별로 차이가 큽니다. SpaceX 비상장 가치 평가가 핵심 변수.',
     "Daily-updated Forbes/Bloomberg net worth figures vary significantly by source. SpaceX private valuation is the key variable."),
    ('출처', 'Source'),
    ('현재 추정', 'Current'),
    ('SpaceX 가정 가치', 'SpaceX assumed'),
    ('IPO 직후 (Base)', 'Post-IPO (Base)'),
    ('가정', 'assumed'),
    ('xAI합병 후', 'post xAI'),
    ('우리 추정 (Sacra·PitchBook)', 'Our estimate (Sacra/PitchBook)'),
    ('왜 출처별 차이가 큰가', 'Why the source spread'),
    ('Forbes 는 보수적으로 비상장 회사를 마지막 펀딩 라운드 가치로 고정 (IPO 가치는 반영 안 함). Bloomberg 는 secondary market 거래가를 반영. 우리 추정은 PitchBook · Sacra 의 strategic premium 을 포함.',
     "Forbes uses last-funding-round valuations for private firms. Bloomberg includes secondary trades. Our estimate adds the PitchBook/Sacra strategic premium."),
    ('중요:', 'Important:'),
    ('IPO 가 실현되어 시장가가 형성되면', 'Once IPO trading establishes a market price,'),
    ('3 출처가 빠르게 수렴', 'all three sources converge fast'),
    ('. Forbes 가 다음날 +$300~400B 점프할 수 있음.', '. Forbes could jump +$300-400B overnight.'),
    ('머스크의 자산은 6개 회사 지분 + 현금/부동산. SpaceX 가 70%+ 차지.',
     "Musk's wealth = 6 company stakes + cash/property. SpaceX accounts for 70%+."),
    ('보유', 'stake'),
    ('합병 후 희석 反映', 'post xAI dilution applied'),
    ('2024 보상 패키지 후', 'post 2024 comp package'),
    ('인수 $44B 대비 mark-down', 'acquisition $44B mark-down'),
    ('펀딩 $5B valuation 가정', 'funding $5B valuation'),
    ('현금·기타', 'Cash · Other'),
    ('유동자산', 'Liquid'),
    ('대부분 주식담보 대출 ($30B+)', 'Mostly stock-backed loans ($30B+)'),
    ('주의: xAI 는 별도가 아님', 'Note: xAI Is Not Separate'),
    ('2026.02 SpaceX 가 xAI 를 전량 주식교환으로 흡수했기 때문에,', 'Because SpaceX absorbed xAI via all-stock swap in Feb 2026,'),
    ('xAI 가치 ($250B 합병가) 는 이미 SpaceX 시가총액에 반영', 'xAI value ($250B merger) is already reflected in the SpaceX cap'),
    ('되어 있습니다. 머스크는 xAI 의 별도 지분을 보유하지 않으며, 그 만큼 SpaceX 신주식을 받았습니다.',
     ". Musk doesn't hold a separate xAI stake; he received SpaceX new shares instead."),
    ('Bloomberg / Forbes 의 일부 보고서가 이를 이중 계산하는 경우가 있어 실제보다 +$100B 과대평가하는 사례 존재.',
     'Some Bloomberg/Forbes reports double-count this, overstating by +$100B.'),
    ('SpaceX 시가총액에 따라 극단적 차이.', 'Drastic differences depending on SpaceX market cap.'),
    ('SpaceX $1.0T (저평가)', 'SpaceX $1.0T (low)'),
    ('SpaceX $1.75T (Target)', 'SpaceX $1.75T (target)'),
    ('SpaceX $2.5T (성공)', 'SpaceX $2.5T (success)'),
    ('+ 기타', '+ others'),
    ('Base 시나리오 detail', 'Base Scenario Detail'),
    ('이 숫자는', 'This number'),
    ('IPO 직후 며칠 내 도달 추정', 'is the estimated value within days post-IPO'),
    ('. 시간이 지나며 첫 분기 실적 발표, lock-up 종료 등에 따라 ±20% 변동성 예상.',
     '. Expect ±20% volatility from earnings & lock-up expiration over time.'),
    ('"트릴리오네어" 가능성', '"Trillionaire" Probability'),
    ('$1조 (1 trillion) 자산은 인류 역사상 처음. 언제·얼마 시점인가.',
     '$1 trillion in personal wealth — first in history. When and how?'),
    ('두 경로', 'Three Paths'),
    ('경로 A — IPO Bull case 즉시:', 'Path A — Immediate via IPO Bull case:'),
    ('SpaceX 가 IPO day 에 $2.5T 까지 가면 Bull 시나리오 ($1.35T) 즉시 도달. 가능성 25~30%.',
     'If SpaceX reaches $2.5T on IPO day, Bull scenario ($1.35T) immediate. Probability 25-30%.'),
    ('경로 B — Base 에서 자연 성장:', 'Path B — Organic growth from Base:'),
    ('$936B 에서 출발해 연 7~10% 자산 증가 시', 'Starting at $936B with 7-10% annual asset growth,'),
    ('2027~2028 사이 $1T 돌파', 'crosses $1T between 2027-2028'),
    ('. 가능성 60~70%.', '. Probability 60-70%.'),
    ('경로 C — Bear 에서 회복:', 'Path C — Recovery from Bear:'),
    ('$640B 에서 시작하면 $1T 도달까지 5~7년 소요. 가능성 20~30%.',
     'Starting at $640B, $1T takes 5-7 years. Probability 20-30%.'),
    ('Forbes 1위 자리는 누가', 'Who Holds Forbes #1'),
    ('2026.05 기준 1위는 머스크 (~$485B). 2위는 Bezos (~$280B), 3위는 Arnault (~$200B).',
     'As of May 2026, #1 is Musk (~$485B), #2 Bezos (~$280B), #3 Arnault (~$200B).'),
    ('IPO 후 머스크 격차는', "Post-IPO Musk's lead widens to"),
    ('2위와 $500B+', '$500B+ over #2'),
    ('로 벌어집니다. 단일 인물이 글로벌 부의 분배에 주는 영향이 역사상 최대.',
     '. The largest single-person impact on global wealth distribution in history.'),
    ('역사적 1위 비교', 'Historical #1 Comparison'),
    ('인플레이션 보정 기준, 머스크는 이미 Rockefeller 시대를 넘어섰습니다.',
     'Inflation-adjusted, Musk has already surpassed the Rockefeller era.'),
    ('인물', 'Person'),
    ('당시 자산', 'Then-Worth'),
    ('2026 가치 환산', '2026 dollars'),
    ('머스크 IPO 직후 Base', 'Musk post-IPO Base'),
    ('머스크 Bull 시나리오', 'Musk Bull scenario'),
    ('자산 ≠ 현금', 'Net Worth ≠ Cash'),
    ('머스크가 $1조라고 해서 $1조를 쓸 수 있다는 뜻은 아닙니다.',
     "$1 trillion in net worth doesn't mean $1 trillion to spend."),
    ('① 유동성 제약', '① Liquidity Constraints'),
    ('자산의 95%+ 가 자기 회사 주식. 매도 시 ① CEO 시그널 효과로 주가 -10~20% ② SEC 14A-3 신고 ③ insider trading 윈도우 제한.',
     "95%+ of wealth is in his own company stock. Selling triggers CEO signal -10-20% drop, SEC 14A-3 filings, insider trading windows."),
    ('② 주식담보 대출 ($30B+)', '② Stock-Backed Loans ($30B+)'),
    ('머스크는 이미 Tesla / SpaceX 주식 담보로 약 $30B 이상 대출 중 (X 인수 자금 포함).',
     'Musk already has $30B+ in loans collateralized by Tesla/SpaceX stock (incl. X acquisition).'),
    ('주가 -50% 시 마진콜 위험', 'Margin call risk at -50% price drop'),
    ('③ 세금', '③ Taxes'),
    ('2021년 옵션 행사로 단일 연도 세금', 'In 2021, options exercise drove a single-year tax of'),
    ('납부 (미국 역사상 개인 1위). IPO 후 자산을 처분하면 long-term capital gains 20%+ 적용.',
     ' (largest individual US tax ever). Post-IPO disposals trigger 20%+ long-term capital gains.'),
    ('④ 자선·기부 약속', '④ Philanthropy Pledges'),
    ('머스크는 Giving Pledge 서명자 (Bezos·Gates 와 함께). 이론상 자산의 50%+ 를 자선에 기부할 의무. 현재 기부 실적은 ~$8B (자산의 약 1.5%).',
     "Musk signed the Giving Pledge (alongside Bezos/Gates), theoretically committing 50%+ to philanthropy. Cumulative donations: ~$8B (~1.5% of net worth)."),
    ('🚀 SpaceX IPO 허브', '🚀 SpaceX IPO Hub'),
    ('관련 콘텐츠', 'Related content'),
    ('$1.75T 심층분석', '$1.75T Deep Dive'),
    ('사는 법', 'How to Buy'),
    ('위험 7가지', '7 Risks'),
    ('투자 시뮬레이터', 'Invest Simulator'),
    ('href="/blog/spacex-ipo-2026/"', 'href="/blog/spacex-ipo-2026-en/"'),
    ('href="/blog/how-to-buy-spacex-stock/"', 'href="/blog/how-to-buy-spacex-stock-en/"'),
    ('href="/blog/spacex-ipo-risks/"', 'href="/blog/spacex-ipo-risks-en/"'),
    ('href="/tools/spacex-invest-sim/"', 'href="/tools/spacex-invest-sim-en/"'),
    ('href="/tools/spacex-countdown/"', 'href="/tools/spacex-countdown-en/"'),
    ('href="/blog/?cat=industry"', 'href="/blog/?cat=industry&amp;lang=en"'),
    ('본 문서는 정보 제공용 분석이며 투자 권유가 아닙니다. 모든 지분 비율 (SpaceX 42%, Tesla 13%, X 80% 등) 은 2026.05 시점 공시·보도 기반 추정. 실제 비율은 보상 패키지 행사·신주 발행·세금 처분 등으로 변동. SpaceX 의 실제 가치와 머스크 지분은 공식 S-1 공개 시 확정. 머스크 자산은 매일 변동하며, 본 추정은 IPO 직후 첫 거래일 종가 기준 시나리오.',
     'Informational analysis only — not investment advice. Stake percentages (SpaceX 42%, Tesla 13%, X 80%, etc.) are 2026.05 estimates based on filings/reporting. Actuals vary with comp packages, new issuance, tax disposals. SpaceX value and Musk stake will be confirmed at S-1. Net worth fluctuates daily; this estimate uses IPO first-day-close as reference.'),
    ('Last updated · 2026.05.05 · v1.0 · <a href="/blog/?cat=industry">← 산업 더보기</a>',
     'Last updated · 2026.05.05 · v1.0 · <a href="/blog/?cat=industry&amp;lang=en">← More Industry</a>'),
]

count = 0
for old, new in swaps:
    if old in h:
        h = h.replace(old, new)
        count += 1
print('Applied', count, 'swaps')
with open(dst, 'w', encoding='utf-8') as f:
    f.write(h)
print('EN file:', dst)
